import type {
  AgentStartTypeDropdownOption,
  ClockSettings,
  ColorRandomizationSettings,
  ColorSettings,
  DisplayTextureAspectRatioDropdownOption,
  LoadableClockSettings,
  LoadableColorSettings,
  LoadableSimulationSettings,
  LoadableSlimeStoreSettings,
  MultipleSimulationPresetType,
  NumericRangeRandomizationSetting,
  OptionListRandomizationSettings,
  PaletteCycleTypeOption,
  ProceduralColorPaletteChannel,
  RandomizationPreset,
  SimulationSettings,
  SingleSimulationPresetType,
} from "../types/types";

type ControlsConfigs<T> = {
  [K in keyof T]?: { min: T[K]; max: T[K]; step: number };
};

export const DEFAULT_CLOCK_SETTINGS: ClockSettings = {
  show: true,
  size: 50,
  digitLayout: "not set",
  hourFormat: "24h",
  digitStyle: "roboto",
  padHours: true,
  showClockShadow: true,
  clockShadowOpacity: 0.1,
  clockShadowColor: "#6f6f6f",
  digitFadeSpeed: 1.0,
};
export const CLOCK_CONTROLS_CONFIGS: ControlsConfigs<ClockSettings> = {
  size: { min: 1, max: 100, step: 1 },
  clockShadowOpacity: { min: 0, max: 1, step: 0.01 },
  digitFadeSpeed: { min: 0.1, max: 5.0, step: 0.1 },
};

export const DEFAULT_SIMULATION_SETTINGS_PRESET_NAME = "Slimy 01";
// TODO: Replace the values in DEFAULT_SIMULATION_SETTINGS that get set
// by the `InitializationHandler` component with some sort of easily-identifiable
// placeholder values (like -1 or -999 or something). Consider commenting on these
// values too so you don't have to keep looking them up.
export const DEFAULT_SIMULATION_SETTINGS: SimulationSettings = {
  settingsSetPreviously: false,

  speed: 3.3,

  boundaryBehavior: 0, // 0: Wrap, 1: Bounce

  agentDensity: 0.25,
  gpuTextureWidth: 16,
  gpuTextureHeight: 16,
  agentStartType: -1,
  agentClockAttraction: 0.05,
  agentClockDepositRate: 6.5,
  agentBackgroundDepositRate: 6.5,
  agentSensorDegrees: 25,
  agentRotationRate: 2.2,
  agentSensorOffset: 19,
  agentSensorWidth: 4,
  agentStepSize: 15,
  agentCrowdAvoidance: 0.1,
  agentWanderStrength: 5.3,

  displayTextureAspectRatio: "Window",
  displayTextureTargetQuality: 1.0,
  displayTextureWidth: -1,
  displayTextureHeight: -1,
  trailClockDecayRate: 0.05,
  trailClockDiffuseRate: 4.5,
  trailBackgroundDecayRate: 0.39,
  trailBackgroundDiffuseRate: 11.7,

  showTextureDisplayPlanes: true,
};

export const SIMULATION_CONTROLS_CONFIGS: ControlsConfigs<SimulationSettings> =
  {
    speed: { min: 0.1, max: 10, step: 0.1 },

    agentClockAttraction: { min: 0.0, max: 1.0, step: 0.01 },
    agentClockDepositRate: { min: 0.0, max: 30.0, step: 0.1 },
    agentBackgroundDepositRate: { min: 0.0, max: 30.0, step: 0.1 },
    agentSensorDegrees: { min: 0.0, max: 180.0, step: 1.0 },
    agentRotationRate: { min: 0.0, max: 10.0, step: 0.1 },
    agentSensorOffset: { min: 0.0, max: 100.0, step: 1.0 },
    agentSensorWidth: { min: 0.0, max: 100.0, step: 1.0 },
    agentStepSize: { min: 0.0, max: 100.0, step: 1.0 },
    agentCrowdAvoidance: { min: 0.0, max: 1.0, step: 0.01 },
    agentWanderStrength: { min: 0.0, max: 15.0, step: 0.1 },

    displayTextureTargetQuality: { min: 0.1, max: 10.0, step: 0.1 },
    trailClockDecayRate: { min: 0.0, max: 2.0, step: 0.01 },
    trailClockDiffuseRate: { min: 0.0, max: 30.0, step: 0.1 },
    trailBackgroundDecayRate: { min: 0.0, max: 2.0, step: 0.01 },
    trailBackgroundDiffuseRate: { min: 0.0, max: 30.0, step: 0.1 },
  };

export const AGENT_START_TYPE_DROPDOWN_OPTIONS: AgentStartTypeDropdownOption[] =
  [
    { value: "-1", label: "Random" },
    { value: "0", label: "Center" },
    { value: "1", label: "Ring" },
    { value: "2", label: "9 Rings" },
    { value: "3", label: "Circle" },
    { value: "4", label: "Spiral" },
    { value: "5", label: "Fill" },
    { value: "6", label: "Hexagonal Grid" },
  ] as const;

export const RANDOMIZATION_SETTINGS_AGENT_START_TYPE_OPTIONS: Record<
  string,
  { enabled: boolean; value: string; label: string }
> = AGENT_START_TYPE_DROPDOWN_OPTIONS.reduce(
  (acc, option) => {
    if (option.label === "Random") return acc;
    acc[option.label] = { ...option, enabled: true };
    return acc;
  },
  {} as Record<string, { enabled: boolean; value: string; label: string }>,
);

const DEFAULT_PROCEDURAL_COLOR_PALETTE_RANDOMIZATION_SETTINGS: {
  yOffset: NumericRangeRandomizationSetting;
  amplitude: NumericRangeRandomizationSetting;
  frequency: NumericRangeRandomizationSetting;
  phase: NumericRangeRandomizationSetting;
} = {
  yOffset: {
    type: "numericRange",
    enabled: true,
    flatRange: [0.0, 1.0],
    gaussMu: 0.5,
    gaussSigma: 0.15,
    pertMinModeMax: [0.25, 0.5, 0.75],
    mode: "pert",
  },
  amplitude: {
    type: "numericRange",
    enabled: true,
    flatRange: [0.05, 0.95],
    gaussMu: 0.5,
    gaussSigma: 0.15,
    pertMinModeMax: [0.25, 0.5, 0.75],
    mode: "pert",
  },
  frequency: {
    type: "numericRange",
    enabled: true,
    flatRange: [0.1, 3.0],
    gaussMu: 1.0,
    gaussSigma: 0.3,
    pertMinModeMax: [0.5, 1.0, 2.0],
    mode: "pert",
  },
  phase: {
    type: "numericRange",
    enabled: true,
    flatRange: [0.0, 3.14],
    gaussMu: 1.57,
    gaussSigma: 0.5,
    pertMinModeMax: [0.0, 1.57, 3.14],
    mode: "pert",
  },
};
export const DEFAULT_COLOR_RANDOMIZATION_SETTINGS: ColorRandomizationSettings =
  {
    backgroundColor: { type: "color", enabled: true },
    proceduralColorPalette: {
      r: DEFAULT_PROCEDURAL_COLOR_PALETTE_RANDOMIZATION_SETTINGS,
      g: DEFAULT_PROCEDURAL_COLOR_PALETTE_RANDOMIZATION_SETTINGS,
      b: DEFAULT_PROCEDURAL_COLOR_PALETTE_RANDOMIZATION_SETTINGS,
    },
    intensitySmoothing: {
      type: "numericRange",
      enabled: false,
      flatRange: [0.4, 0.6],
      gaussMu: 0.5,
      gaussSigma: 0.03,
      pertMinModeMax: [0.25, 0.5, 0.75],
      mode: "pert",
    },
    agentDirectionSmoothing: {
      type: "numericRange",
      enabled: false,
      flatRange: [0.4, 0.6],
      gaussMu: 0.5,
      gaussSigma: 0.03,
      pertMinModeMax: [0.25, 0.5, 0.75],
      mode: "pert",
    },
    agentDirectionColorOffset: {
      type: "numericRange",
      enabled: true,
      flatRange: [-0.2, 0.2],
      gaussMu: 0.0,
      gaussSigma: 0.1,
      pertMinModeMax: [-0.2, 0.0, 0.2],
      mode: "pert",
    },
    clockColorOffset: {
      type: "numericRange",
      enabled: false,
      flatRange: [0.05, 0.25],
      gaussMu: 0.15,
      gaussSigma: 0.03,
      pertMinModeMax: [0.05, 0.15, 0.25],
      mode: "pert",
    },
    xColorOffset: {
      type: "numericRange",
      enabled: true,
      flatRange: [-0.5, 0.5],
      gaussMu: 0.0,
      gaussSigma: 0.9,
      pertMinModeMax: [-0.5, 0.0, 0.5],
      mode: "pert",
    },
    yColorOffset: {
      type: "numericRange",
      enabled: true,
      flatRange: [-0.5, 0.5],
      gaussMu: 0.0,
      gaussSigma: 0.9,
      pertMinModeMax: [-0.5, 0.0, 0.5],
      mode: "pert",
    },
    paletteCycleSpeed: {
      type: "numericRange",
      enabled: true,
      flatRange: [0.2, 0.8],
      gaussMu: 0.5,
      gaussSigma: 0.15,
      pertMinModeMax: [0.2, 0.5, 0.8],
      mode: "pert",
    },
    paletteCycleScale: {
      type: "numericRange",
      enabled: false,
      flatRange: [0.05, 0.25],
      gaussMu: 0.15,
      gaussSigma: 0.03,
      pertMinModeMax: [0.05, 0.15, 0.25],
      mode: "pert",
    },
  };

export const AGENT_START_TYPE_RANDOMIZATION_SETTINGS: OptionListRandomizationSettings =
  {
    type: "optionList",
    enabled: true,
    options: {
      Center: {
        value: "0",
        label: "Center",
        enabled: true,
      },
      Ring: {
        value: "1",
        label: "Ring",
        enabled: true,
      },
      "9 Rings": {
        value: "2",
        label: "9 Rings",
        enabled: true,
      },
      Circle: {
        value: "3",
        label: "Circle",
        enabled: true,
      },
      Spiral: {
        value: "4",
        label: "Spiral",
        enabled: true,
      },
      Fill: {
        value: "5",
        label: "Fill",
        enabled: true,
      },
      "Hexagonal Grid": {
        value: "6",
        label: "Hexagonal Grid",
        enabled: true,
      },
    },
  };

export const DEFAULT_SIMULATION_RANDOMIZATION_SETTINGS_PRESET_NAME = "Slimy 01";
export const DEFAULT_COLOR_RANDOMIZATION_SETTINGS_PRESET_NAME = "Colorful";
export const RANDOMIZATION_PRESETS: RandomizationPreset[] = [
  {
    presetType: "simulation",
    name: "Slimy 01",
    enabled: true,
    isBasePreset: true,
    settings: {
      agentClockAttraction: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.14, 0.22],
        gaussMu: 0.17,
        gaussSigma: 0.03,
        pertMinModeMax: [0.11, 0.17, 0.34],
        mode: "pert",
      },
      agentClockDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [6.73, 9.65],
        gaussMu: 8.02,
        gaussSigma: 2.49,
        pertMinModeMax: [3.7, 7.95, 11.9],
        mode: "pert",
      },
      agentBackgroundDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [9.33, 12.25],
        gaussMu: 10.72,
        gaussSigma: 2.23,
        pertMinModeMax: [6.1, 11.1, 14.8],
        mode: "pert",
      },
      agentSensorDegrees: {
        type: "numericRange",
        enabled: true,
        flatRange: [22, 31.25],
        gaussMu: 30,
        gaussSigma: 10.72,
        pertMinModeMax: [17, 28.5, 60],
        mode: "pert",
      },
      agentRotationRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2.78, 3.8],
        gaussMu: 3.26,
        gaussSigma: 0.86,
        pertMinModeMax: [1.1, 3.35, 4.6],
        mode: "pert",
      },
      agentSensorOffset: {
        type: "numericRange",
        enabled: true,
        flatRange: [9, 15],
        gaussMu: 12,
        gaussSigma: 4,
        pertMinModeMax: [7, 11, 20],
        mode: "pert",
      },
      agentSensorWidth: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 3],
        gaussMu: 2,
        gaussSigma: 1,
        pertMinModeMax: [1, 2, 3],
        mode: "pert",
      },
      agentStepSize: {
        type: "numericRange",
        enabled: true,
        flatRange: [15, 21],
        gaussMu: 18,
        gaussSigma: 3,
        pertMinModeMax: [13, 17, 24],
        mode: "pert",
      },
      agentCrowdAvoidance: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.17, 0.37],
        gaussMu: 0.28,
        gaussSigma: 0.12,
        pertMinModeMax: [0.09, 0.26, 0.5],
        mode: "pert",
      },
      agentWanderStrength: {
        type: "numericRange",
        enabled: true,
        flatRange: [4.2, 6.98],
        gaussMu: 5.29,
        gaussSigma: 2.23,
        pertMinModeMax: [0.4, 5.1, 8.7],
        mode: "pert",
      },
      trailClockDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.03, 0.07],
        gaussMu: 0.05,
        gaussSigma: 0.01,
        pertMinModeMax: [0.01, 0.04, 0.07],
        mode: "pert",
      },
      trailClockDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [4.1, 7.18],
        gaussMu: 5.83,
        gaussSigma: 2.27,
        pertMinModeMax: [2.1, 5.75, 9.9],
        mode: "pert",
      },
      trailBackgroundDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.39, 0.57],
        gaussMu: 0.49,
        gaussSigma: 0.12,
        pertMinModeMax: [0.34, 0.42, 0.75],
        mode: "pert",
      },
      trailBackgroundDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [4.18, 11.05],
        gaussMu: 8.42,
        gaussSigma: 3.69,
        pertMinModeMax: [1.9, 10.2, 14.1],
        mode: "pert",
      },
    },
  },
  {
    presetType: "simulation",
    name: "Inverted 01",
    enabled: true,
    isBasePreset: true,
    settings: {
      agentClockAttraction: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.59, 0.73],
        gaussMu: 0.58,
        gaussSigma: 0.2,
        pertMinModeMax: [0.2, 0.65, 0.75],
        mode: "pert",
      },
      agentClockDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [3.3, 3.5],
        gaussMu: 3.58,
        gaussSigma: 0.49,
        pertMinModeMax: [3.1, 3.5, 4.5],
        mode: "pert",
      },
      agentBackgroundDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [10.8, 11.7],
        gaussMu: 11.26,
        gaussSigma: 0.48,
        pertMinModeMax: [10.7, 11.2, 11.9],
        mode: "pert",
      },
      agentSensorDegrees: {
        type: "numericRange",
        enabled: true,
        flatRange: [48, 61],
        gaussMu: 52,
        gaussSigma: 15.63,
        pertMinModeMax: [24, 58, 69],
        mode: "pert",
      },
      agentRotationRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [6.5, 6.9],
        gaussMu: 6.34,
        gaussSigma: 1.04,
        pertMinModeMax: [4.3, 6.9, 7.1],
        mode: "pert",
      },
      agentSensorOffset: {
        type: "numericRange",
        enabled: true,
        flatRange: [11, 12],
        gaussMu: 13,
        gaussSigma: 3,
        pertMinModeMax: [10, 11, 20],
        mode: "pert",
      },
      agentSensorWidth: {
        type: "numericRange",
        enabled: true,
        flatRange: [4, 5],
        gaussMu: 5,
        gaussSigma: 1,
        pertMinModeMax: [3, 5, 7],
        mode: "pert",
      },
      agentStepSize: {
        type: "numericRange",
        enabled: true,
        flatRange: [15, 21],
        gaussMu: 18,
        gaussSigma: 3,
        pertMinModeMax: [13, 17, 24],
        mode: "pert",
      },
      agentCrowdAvoidance: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.39, 0.44],
        gaussMu: 0.43,
        gaussSigma: 0.05,
        pertMinModeMax: [0.37, 0.43, 0.51],
        mode: "pert",
      },
      agentWanderStrength: {
        type: "numericRange",
        enabled: true,
        flatRange: [1.6, 2.6],
        gaussMu: 2.16,
        gaussSigma: 0.97,
        pertMinModeMax: [1, 1.8, 3.8],
        mode: "pert",
      },
      trailClockDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.47, 0.5],
        gaussMu: 0.53,
        gaussSigma: 0.15,
        pertMinModeMax: [0.37, 0.49, 0.8],
        mode: "pert",
      },
      trailClockDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2.4, 2.9],
        gaussMu: 2.82,
        gaussSigma: 0.62,
        pertMinModeMax: [2.1, 2.8, 3.9],
        mode: "pert",
      },
      trailBackgroundDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.08, 0.27],
        gaussMu: 0.18,
        gaussSigma: 0.09,
        pertMinModeMax: [0.07, 0.18, 0.29],
        mode: "pert",
      },
      trailBackgroundDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [6.2, 8],
        gaussMu: 7.4,
        gaussSigma: 1.59,
        pertMinModeMax: [5.3, 7.6, 9.9],
        mode: "pert",
      },
    },
  },
  {
    presetType: "simulation",
    name: "[Test] Inverted Wavy 01",
    enabled: false,
    isBasePreset: true,
    settings: {
      agentClockAttraction: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.02, 0.07],
        gaussMu: 0.05,
        gaussSigma: 0.03,
        pertMinModeMax: [0.47, 0.69, 0.9],
        mode: "pert",
      },
      agentClockDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 15],
        gaussMu: 8,
        gaussSigma: 3,
        pertMinModeMax: [1.8, 4, 6.5],
        mode: "pert",
      },
      agentBackgroundDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 15],
        gaussMu: 8,
        gaussSigma: 3,
        pertMinModeMax: [8.6, 12.2, 15.6],
        mode: "pert",
      },
      agentSensorDegrees: {
        type: "numericRange",
        enabled: true,
        flatRange: [15, 45],
        gaussMu: 25,
        gaussSigma: 5,
        pertMinModeMax: [37, 66, 80],
        mode: "pert",
      },
      agentRotationRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [1, 5],
        gaussMu: 3,
        gaussSigma: 0.75,
        pertMinModeMax: [5.4, 7.2, 8.4],
        mode: "pert",
      },
      agentSensorOffset: {
        type: "numericRange",
        enabled: true,
        flatRange: [5, 25],
        gaussMu: 12,
        gaussSigma: 3,
        pertMinModeMax: [7, 11, 21],
        mode: "pert",
      },
      agentSensorWidth: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 8],
        gaussMu: 3,
        gaussSigma: 1,
        pertMinModeMax: [2, 5, 9],
        mode: "pert",
      },
      agentStepSize: {
        type: "numericRange",
        enabled: true,
        flatRange: [5, 25],
        gaussMu: 12,
        gaussSigma: 3,
        pertMinModeMax: [10, 18, 26],
        mode: "pert",
      },
      agentCrowdAvoidance: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.05, 0.5],
        gaussMu: 0.15,
        gaussSigma: 0.08,
        pertMinModeMax: [0.3, 0.46, 0.58],
        mode: "pert",
      },
      agentWanderStrength: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.1, 10],
        gaussMu: 5,
        gaussSigma: 1.5,
        pertMinModeMax: [0.5, 1.4, 3.2],
        mode: "pert",
      },
      trailClockDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.01, 0.5],
        gaussMu: 0.1,
        gaussSigma: 0.1,
        pertMinModeMax: [0.28, 0.47, 1.04],
        mode: "pert",
      },
      trailClockDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 10],
        gaussMu: 8,
        gaussSigma: 2.5,
        pertMinModeMax: [0.5, 3, 8.4],
        mode: "pert",
      },
      trailBackgroundDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.01, 0.8],
        gaussMu: 0.5,
        gaussSigma: 0.1,
        pertMinModeMax: [0.06, 0.19, 0.48],
        mode: "pert",
      },
      trailBackgroundDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 15],
        gaussMu: 8,
        gaussSigma: 2.5,
        pertMinModeMax: [4.1, 6.4, 13.2],
        mode: "pert",
      },
    },
  },
  {
    presetType: "simulation",
    name: "[Test] Basic Slimy 01",
    enabled: false,
    isBasePreset: true,
    settings: {
      agentClockAttraction: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.02, 0.07],
        gaussMu: 0.05,
        gaussSigma: 0.03,
        pertMinModeMax: [0, 0.05, 0.15],
        mode: "pert",
      },
      agentClockDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 15],
        gaussMu: 8,
        gaussSigma: 3,
        pertMinModeMax: [4.8, 8.3, 11.3],
        mode: "pert",
      },
      agentBackgroundDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 15],
        gaussMu: 8,
        gaussSigma: 3,
        pertMinModeMax: [3, 7.3, 10.4],
        mode: "pert",
      },
      agentSensorDegrees: {
        type: "numericRange",
        enabled: true,
        flatRange: [15, 45],
        gaussMu: 25,
        gaussSigma: 5,
        pertMinModeMax: [13, 21, 36],
        mode: "pert",
      },
      agentRotationRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [1, 5],
        gaussMu: 3,
        gaussSigma: 0.75,
        pertMinModeMax: [1.7, 3, 4.5],
        mode: "pert",
      },
      agentSensorOffset: {
        type: "numericRange",
        enabled: true,
        flatRange: [5, 25],
        gaussMu: 12,
        gaussSigma: 3,
        pertMinModeMax: [7, 11, 20],
        mode: "pert",
      },
      agentSensorWidth: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 8],
        gaussMu: 3,
        gaussSigma: 1,
        pertMinModeMax: [1, 2, 6],
        mode: "pert",
      },
      agentStepSize: {
        type: "numericRange",
        enabled: true,
        flatRange: [5, 25],
        gaussMu: 12,
        gaussSigma: 3,
        pertMinModeMax: [9, 13, 18],
        mode: "pert",
      },
      agentCrowdAvoidance: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.05, 0.5],
        gaussMu: 0.15,
        gaussSigma: 0.08,
        pertMinModeMax: [0.1, 0.2, 0.32],
        mode: "pert",
      },
      agentWanderStrength: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.1, 10],
        gaussMu: 5,
        gaussSigma: 1.5,
        pertMinModeMax: [3.8, 6.5, 9.5],
        mode: "pert",
      },
      trailClockDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.01, 0.5],
        gaussMu: 0.1,
        gaussSigma: 0.1,
        pertMinModeMax: [0.01, 0.05, 0.13],
        mode: "pert",
      },
      trailClockDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 10],
        gaussMu: 8,
        gaussSigma: 2.5,
        pertMinModeMax: [3.9, 7.8, 11.6],
        mode: "pert",
      },
      trailBackgroundDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.01, 0.8],
        gaussMu: 0.5,
        gaussSigma: 0.1,
        pertMinModeMax: [0.28, 0.48, 0.78],
        mode: "pert",
      },
      trailBackgroundDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 15],
        gaussMu: 8,
        gaussSigma: 2.5,
        pertMinModeMax: [6.5, 10.6, 13.9],
        mode: "pert",
      },
    },
  },
  {
    presetType: "simulation",
    name: "[Test] Small Wavy Slime 01",
    enabled: false,
    isBasePreset: true,
    settings: {
      agentClockAttraction: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.02, 0.07],
        gaussMu: 0.05,
        gaussSigma: 0.03,
        pertMinModeMax: [0.12, 0.27, 0.41],
        mode: "pert",
      },
      agentClockDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 15],
        gaussMu: 8,
        gaussSigma: 3,
        pertMinModeMax: [1.9, 3.7, 6.5],
        mode: "pert",
      },
      agentBackgroundDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 15],
        gaussMu: 8,
        gaussSigma: 3,
        pertMinModeMax: [7.8, 11, 14.5],
        mode: "pert",
      },
      agentSensorDegrees: {
        type: "numericRange",
        enabled: true,
        flatRange: [15, 45],
        gaussMu: 25,
        gaussSigma: 5,
        pertMinModeMax: [19, 47, 71],
        mode: "pert",
      },
      agentRotationRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [1, 5],
        gaussMu: 3,
        gaussSigma: 0.75,
        pertMinModeMax: [2.1, 3.8, 6.1],
        mode: "pert",
      },
      agentSensorOffset: {
        type: "numericRange",
        enabled: true,
        flatRange: [5, 25],
        gaussMu: 12,
        gaussSigma: 3,
        pertMinModeMax: [6, 10, 20],
        mode: "pert",
      },
      agentSensorWidth: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 8],
        gaussMu: 3,
        gaussSigma: 1,
        pertMinModeMax: [1, 3, 10],
        mode: "pert",
      },
      agentStepSize: {
        type: "numericRange",
        enabled: true,
        flatRange: [5, 25],
        gaussMu: 12,
        gaussSigma: 3,
        pertMinModeMax: [11, 22, 33],
        mode: "pert",
      },
      agentCrowdAvoidance: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.05, 0.5],
        gaussMu: 0.15,
        gaussSigma: 0.08,
        pertMinModeMax: [0.19, 0.3, 0.52],
        mode: "pert",
      },
      agentWanderStrength: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.1, 10],
        gaussMu: 5,
        gaussSigma: 1.5,
        pertMinModeMax: [2.8, 4.6, 6.5],
        mode: "pert",
      },
      trailClockDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.01, 0.5],
        gaussMu: 0.1,
        gaussSigma: 0.1,
        pertMinModeMax: [0.01, 0.03, 0.1],
        mode: "pert",
      },
      trailClockDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 10],
        gaussMu: 8,
        gaussSigma: 2.5,
        pertMinModeMax: [0.5, 3.5, 8.4],
        mode: "pert",
      },
      trailBackgroundDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.01, 0.8],
        gaussMu: 0.5,
        gaussSigma: 0.1,
        pertMinModeMax: [0.21, 0.45, 1.25],
        mode: "pert",
      },
      trailBackgroundDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 15],
        gaussMu: 8,
        gaussSigma: 2.5,
        pertMinModeMax: [4.1, 8.7, 13.2],
        mode: "pert",
      },
    },
  },
  {
    presetType: "simulation",
    name: "[Test] Thin Slime 01",
    enabled: false,
    isBasePreset: true,
    settings: {
      agentClockAttraction: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.02, 0.07],
        gaussMu: 0.05,
        gaussSigma: 0.03,
        pertMinModeMax: [0.01, 0.08, 0.16],
        mode: "pert",
      },
      agentClockDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 15],
        gaussMu: 8,
        gaussSigma: 3,
        pertMinModeMax: [6.3, 10.2, 14.7],
        mode: "pert",
      },
      agentBackgroundDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 15],
        gaussMu: 8,
        gaussSigma: 3,
        pertMinModeMax: [7.2, 12.2, 15.9],
        mode: "pert",
      },
      agentSensorDegrees: {
        type: "numericRange",
        enabled: true,
        flatRange: [15, 45],
        gaussMu: 25,
        gaussSigma: 5,
        pertMinModeMax: [5, 20, 45],
        mode: "pert",
      },
      agentRotationRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [1, 5],
        gaussMu: 3,
        gaussSigma: 0.75,
        pertMinModeMax: [1.2, 3.2, 5.3],
        mode: "pert",
      },
      agentSensorOffset: {
        type: "numericRange",
        enabled: true,
        flatRange: [5, 25],
        gaussMu: 12,
        gaussSigma: 3,
        pertMinModeMax: [6, 10, 20],
        mode: "pert",
      },
      agentSensorWidth: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 8],
        gaussMu: 3,
        gaussSigma: 1,
        pertMinModeMax: [1, 3, 10],
        mode: "pert",
      },
      agentStepSize: {
        type: "numericRange",
        enabled: true,
        flatRange: [5, 25],
        gaussMu: 12,
        gaussSigma: 3,
        pertMinModeMax: [11, 22, 32],
        mode: "pert",
      },
      agentCrowdAvoidance: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.05, 0.5],
        gaussMu: 0.15,
        gaussSigma: 0.08,
        pertMinModeMax: [0.01, 0.14, 0.32],
        mode: "pert",
      },
      agentWanderStrength: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.1, 10],
        gaussMu: 5,
        gaussSigma: 1.5,
        pertMinModeMax: [4.3, 7.6, 11],
        mode: "pert",
      },
      trailClockDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.01, 0.5],
        gaussMu: 0.1,
        gaussSigma: 0.1,
        pertMinModeMax: [0.01, 0.08, 0.56],
        mode: "pert",
      },
      trailClockDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 10],
        gaussMu: 8,
        gaussSigma: 2.5,
        pertMinModeMax: [3.9, 9.4, 15],
        mode: "pert",
      },
      trailBackgroundDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.01, 0.8],
        gaussMu: 0.5,
        gaussSigma: 0.1,
        pertMinModeMax: [0.21, 0.49, 1.25],
        mode: "pert",
      },
      trailBackgroundDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 15],
        gaussMu: 8,
        gaussSigma: 2.5,
        pertMinModeMax: [1.2, 4.5, 9.8],
        mode: "pert",
      },
    },
  },
  {
    presetType: "simulation",
    name: "[Test] Wispy Slime 01",
    enabled: false,
    isBasePreset: true,
    settings: {
      agentClockAttraction: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.02, 0.07],
        gaussMu: 0.05,
        gaussSigma: 0.02,
        pertMinModeMax: [0.05, 0.18, 0.31],
        mode: "pert",
      },
      agentClockDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 15],
        gaussMu: 8,
        gaussSigma: 3,
        pertMinModeMax: [4.8, 7.6, 13.4],
        mode: "pert",
      },
      agentBackgroundDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 15],
        gaussMu: 8,
        gaussSigma: 3,
        pertMinModeMax: [5.3, 9.4, 13.5],
        mode: "pert",
      },
      agentSensorDegrees: {
        type: "numericRange",
        enabled: true,
        flatRange: [15, 45],
        gaussMu: 25,
        gaussSigma: 5,
        pertMinModeMax: [5, 17, 45],
        mode: "pert",
      },
      agentRotationRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [1, 5],
        gaussMu: 3,
        gaussSigma: 0.75,
        pertMinModeMax: [0.2, 2.8, 7],
        mode: "pert",
      },
      agentSensorOffset: {
        type: "numericRange",
        enabled: true,
        flatRange: [5, 25],
        gaussMu: 12,
        gaussSigma: 3,
        pertMinModeMax: [11, 16, 34],
        mode: "pert",
      },
      agentSensorWidth: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 8],
        gaussMu: 3,
        gaussSigma: 1,
        pertMinModeMax: [1, 3, 10],
        mode: "pert",
      },
      agentStepSize: {
        type: "numericRange",
        enabled: true,
        flatRange: [5, 25],
        gaussMu: 12,
        gaussSigma: 3,
        pertMinModeMax: [11, 16, 24],
        mode: "pert",
      },
      agentCrowdAvoidance: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.05, 0.5],
        gaussMu: 0.15,
        gaussSigma: 0.08,
        pertMinModeMax: [0.01, 0.41, 0.9],
        mode: "pert",
      },
      agentWanderStrength: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.1, 10],
        gaussMu: 5,
        gaussSigma: 1.5,
        pertMinModeMax: [0, 1.8, 5.4],
        mode: "pert",
      },
      trailClockDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.01, 0.08],
        gaussMu: 0.1,
        gaussSigma: 0.1,
        pertMinModeMax: [0.01, 0.05, 0.1],
        mode: "pert",
      },
      trailClockDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 10],
        gaussMu: 8,
        gaussSigma: 2.5,
        pertMinModeMax: [0.1, 5, 15],
        mode: "pert",
      },
      trailBackgroundDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.01, 0.8],
        gaussMu: 0.5,
        gaussSigma: 0.1,
        pertMinModeMax: [0.01, 0.41, 1.25],
        mode: "pert",
      },
      trailBackgroundDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2, 15],
        gaussMu: 8,
        gaussSigma: 2.5,
        pertMinModeMax: [5.1, 12.9, 20.4],
        mode: "pert",
      },
    },
  },
  {
    presetType: "color",
    name: "Colorful",
    isBasePreset: true,
    enabled: true,
    settings: {
      ...DEFAULT_COLOR_RANDOMIZATION_SETTINGS,
    },
  },
];

export const DEFAULT_COLOR_SETTINGS_PRESET_NAME = "Rainbow";
export const DEFAULT_COLOR_SETTINGS: ColorSettings = {
  settingsSetPreviously: false,
  slimeColorChangedAt: 0,

  backgroundColor: "#70f3eb",
  slimeColorMode: "Procedural",
  proceduralColorPalette: {
    r: { yOffset: 0.5, amplitude: 0.5, frequency: 1.0, phase: 0.0 },
    g: { yOffset: 0.5, amplitude: 0.5, frequency: 1.0, phase: 0.33 },
    b: { yOffset: 0.5, amplitude: 0.5, frequency: 1.0, phase: 0.66 },
  },
  intensitySmoothing: 0.59,
  agentDirectionSmoothing: 0.68,
  agentDirectionColorOffset: 0.42,
  clockColorOffset: 0.64,
  xColorOffset: 0.65,
  yColorOffset: 0.8,
  paletteCycleSpeed: 0.54,
  paletteCycleScale: 0.1,
  paletteCycleType: 1,
};

export const COLOR_CONTROLS_CONFIGS: ControlsConfigs<ColorSettings> = {
  intensitySmoothing: { min: 0.0, max: 1.0, step: 0.01 },
  agentDirectionSmoothing: { min: 0.0, max: 1.0, step: 0.01 },
  agentDirectionColorOffset: { min: -1.0, max: 1.0, step: 0.01 },
  clockColorOffset: { min: -1.0, max: 1.0, step: 0.01 },
  xColorOffset: { min: -1.0, max: 1.0, step: 0.01 },
  yColorOffset: { min: -1.0, max: 1.0, step: 0.01 },
  paletteCycleSpeed: { min: 0.0, max: 1.0, step: 0.01 },
  paletteCycleScale: { min: 0.01, max: 1.0, step: 0.01 },
};

export const PROCEDURAL_COLOR_PALETTE_CONTROLS_CONFIGS: ControlsConfigs<ProceduralColorPaletteChannel> =
  {
    yOffset: { min: 0.0, max: 1.0, step: 0.01 },
    amplitude: { min: 0.0, max: 5.0, step: 0.01 },
    frequency: { min: 0.0, max: 5.0, step: 0.01 },
    phase: {
      min: 0.0,
      max: Math.round(Math.PI * 100) / 100,
      step: 0.01,
    },
  };

const flickerPoints = Array.from({ length: 11 }, (_, i) => i / 10);
const flickerInOpacity = flickerPoints.map((point) =>
  Math.min(
    1,
    Math.max(
      0,
      Math.sin(6 * Math.PI * point) * Math.sin(Math.PI * point) * 0.4 + point,
    ),
  ),
);

export const ANIMATION_CONFIGS = {
  flickerIn: {
    opacity: flickerInOpacity,
    transition: {
      duration: 0.3,
      times: flickerPoints,
      when: "beforeChildren",
    },
  },
  flickerOut: {
    opacity: flickerInOpacity.slice().reverse(),
    transition: {
      duration: 0.3,
      times: flickerPoints,
      when: "afterChildren",
    },
  },
};

export const DISPLAY_TEXTURE_ASPECT_RATIO_OPTIONS: DisplayTextureAspectRatioDropdownOption[] =
  [
    { value: "Window", label: "Window" },
    { value: "16:10", label: "16:10" },
    { value: "16:9", label: "16:9" },
    { value: "4:3", label: "4:3" },
    { value: "3:2", label: "3:2" },
    { value: "1:1", label: "1:1" },
    { value: "2:3", label: "2:3" },
    { value: "3:4", label: "3:4" },
    { value: "9:16", label: "9:16" },
    { value: "10:16", label: "10:16" },
  ] as const;

export const PALETTE_CYCLE_TYPE_OPTIONS: PaletteCycleTypeOption[] = [
  { value: "0", label: "Oscillating" },
  { value: "1", label: "Repeating" },
  { value: "2", label: "Continuous" },
] as const;

export const LOADABLE_CLOCK_SETTINGS_KEYS: (keyof LoadableClockSettings)[] = [
  "show",
  "size",
  "digitLayout",
  "hourFormat",
  "digitStyle",
  "padHours",
  "showClockShadow",
  "clockShadowOpacity",
  "clockShadowColor",
  "digitFadeSpeed",
];
export const LOADABLE_SIMULATION_SETTINGS_KEYS: (keyof LoadableSimulationSettings)[] =
  [
    "speed",
    "boundaryBehavior",
    "agentDensity",
    "agentStartType",
    "agentClockAttraction",
    "agentClockDepositRate",
    "agentBackgroundDepositRate",
    "agentSensorDegrees",
    "agentRotationRate",
    "agentSensorOffset",
    "agentSensorWidth",
    "agentStepSize",
    "agentCrowdAvoidance",
    "agentWanderStrength",
    "trailClockDecayRate",
    "trailClockDiffuseRate",
    "trailBackgroundDecayRate",
    "trailBackgroundDiffuseRate",
  ];
export const LOADABLE_COLOR_SETTINGS_KEYS: (keyof LoadableColorSettings)[] = [
  "backgroundColor",
  "slimeColorMode",
  "proceduralColorPalette",
  "intensitySmoothing",
  "agentDirectionSmoothing",
  "agentDirectionColorOffset",
  "clockColorOffset",
  "xColorOffset",
  "yColorOffset",
  "paletteCycleSpeed",
  "paletteCycleScale",
  "paletteCycleType",
];

export const DEFAULT_PRESETS: LoadableSlimeStoreSettings[] = [
  {
    name: "Horizontal - Small - Roboto",
    presetType: "Clock Only",
    isBasePreset: true,
    clockSettings: {
      show: true,
      size: 30,
      digitLayout: "horizontal",
      hourFormat: "24h",
      digitStyle: "roboto",
      padHours: true,
      showClockShadow: true,
      clockShadowOpacity: 0.1,
      clockShadowColor: "#6f6f6f",
      digitFadeSpeed: 1.0,
    },
  },
  {
    name: "Horizontal - Medium - Roboto",
    presetType: "Clock Only",
    isBasePreset: true,
    clockSettings: {
      show: true,
      size: 50,
      digitLayout: "horizontal",
      hourFormat: "24h",
      digitStyle: "roboto",
      padHours: true,
      showClockShadow: true,
      clockShadowOpacity: 0.1,
      clockShadowColor: "#6f6f6f",
      digitFadeSpeed: 1.0,
    },
  },
  {
    name: "Horizontal - Large - Roboto",
    presetType: "Clock Only",
    isBasePreset: true,
    clockSettings: {
      show: true,
      size: 70,
      digitLayout: "horizontal",
      hourFormat: "24h",
      digitStyle: "roboto",
      padHours: true,
      showClockShadow: true,
      clockShadowOpacity: 0.1,
      clockShadowColor: "#6f6f6f",
      digitFadeSpeed: 1.0,
    },
  },
  {
    name: "Vertical - Small - Roboto",
    presetType: "Clock Only",
    isBasePreset: true,
    clockSettings: {
      show: true,
      size: 20,
      digitLayout: "vertical",
      hourFormat: "24h",
      digitStyle: "roboto",
      padHours: true,
      showClockShadow: true,
      clockShadowOpacity: 0.1,
      clockShadowColor: "#6f6f6f",
      digitFadeSpeed: 1.0,
    },
  },
  {
    name: "Vertical - Medium - Roboto",
    presetType: "Clock Only",
    isBasePreset: true,
    clockSettings: {
      show: true,
      size: 35,
      digitLayout: "vertical",
      hourFormat: "24h",
      digitStyle: "roboto",
      padHours: true,
      showClockShadow: true,
      clockShadowOpacity: 0.1,
      clockShadowColor: "#6f6f6f",
      digitFadeSpeed: 1.0,
    },
  },
  {
    name: "Vertical - Large - Roboto",
    presetType: "Clock Only",
    isBasePreset: true,
    clockSettings: {
      show: true,
      size: 50,
      digitLayout: "vertical",
      hourFormat: "24h",
      digitStyle: "roboto",
      padHours: true,
      showClockShadow: true,
      clockShadowOpacity: 0.1,
      clockShadowColor: "#6f6f6f",
      digitFadeSpeed: 1.0,
    },
  },
  {
    name: "Extra Gooey 01",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.11,
      agentClockDepositRate: 7.4,
      agentBackgroundDepositRate: 14.8,
      agentSensorDegrees: 60,
      agentRotationRate: 4.6,
      agentSensorOffset: 7,
      agentSensorWidth: 2,
      agentStepSize: 23,
      agentCrowdAvoidance: 0.47,
      agentWanderStrength: 2,
      trailClockDecayRate: 0.04,
      trailClockDiffuseRate: 5.7,
      trailBackgroundDecayRate: 0.39,
      trailBackgroundDiffuseRate: 3.7,
    },
  },
  {
    name: "Fuzzy 01",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.04,
      agentClockDepositRate: 11,
      agentBackgroundDepositRate: 12.6,
      agentSensorDegrees: 22,
      agentRotationRate: 2.7,
      agentSensorOffset: 24,
      agentSensorWidth: 4,
      agentStepSize: 13,
      agentCrowdAvoidance: 0.33,
      agentWanderStrength: 9.4,
      trailClockDecayRate: 0.02,
      trailClockDiffuseRate: 9.2,
      trailBackgroundDecayRate: 0.28,
      trailBackgroundDiffuseRate: 10.2,
    },
  },
  {
    name: "Inverted Roiling",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.2,
      agentClockDepositRate: 3.1,
      agentBackgroundDepositRate: 11.9,
      agentSensorDegrees: 24,
      agentRotationRate: 4.3,
      agentSensorOffset: 21,
      agentSensorWidth: 4,
      agentStepSize: 22,
      agentCrowdAvoidance: 0.37,
      agentWanderStrength: 3.8,
      trailClockDecayRate: 0.47,
      trailClockDiffuseRate: 2.4,
      trailBackgroundDecayRate: 0.07,
      trailBackgroundDiffuseRate: 9.9,
    },
  },
  {
    name: "Slimy 01",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.18,
      agentClockDepositRate: 7.6,
      agentBackgroundDepositRate: 9.4,
      agentSensorDegrees: 17,
      agentRotationRate: 2.8,
      agentSensorOffset: 16,
      agentSensorWidth: 3,
      agentStepSize: 22,
      agentCrowdAvoidance: 0.41,
      agentWanderStrength: 0.4,
      trailClockDecayRate: 0.05,
      trailClockDiffuseRate: 5,
      trailBackgroundDecayRate: 0.41,
      trailBackgroundDiffuseRate: 12.9,
    },
  },
  {
    name: "Slimy 02",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.03,
      agentClockDepositRate: 14.5,
      agentBackgroundDepositRate: 5.9,
      agentSensorDegrees: 47,
      agentRotationRate: 1.5,
      agentSensorOffset: 22,
      agentSensorWidth: 4,
      agentStepSize: 13,
      agentCrowdAvoidance: 0.33,
      agentWanderStrength: 0.4,
      trailClockDecayRate: 0.01,
      trailClockDiffuseRate: 4.5,
      trailBackgroundDecayRate: 0.21,
      trailBackgroundDiffuseRate: 5.2,
    },
  },
  {
    name: "Slimy 03",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.05,
      agentClockDepositRate: 10.2,
      agentBackgroundDepositRate: 12.2,
      agentSensorDegrees: 20,
      agentRotationRate: 3.2,
      agentSensorOffset: 10,
      agentSensorWidth: 3,
      agentStepSize: 22,
      agentCrowdAvoidance: 0.12,
      agentWanderStrength: 8,
      trailClockDecayRate: 0.08,
      trailClockDiffuseRate: 9.5,
      trailBackgroundDecayRate: 0.49,
      trailBackgroundDiffuseRate: 4.5,
    },
  },
  {
    name: "Slimy 04",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.27,
      agentClockDepositRate: 3.3,
      agentBackgroundDepositRate: 11,
      agentSensorDegrees: 47,
      agentRotationRate: 3.8,
      agentSensorOffset: 10,
      agentSensorWidth: 3,
      agentStepSize: 22,
      agentCrowdAvoidance: 0.3,
      agentWanderStrength: 4.6,
      trailClockDecayRate: 0.02,
      trailClockDiffuseRate: 3.5,
      trailBackgroundDecayRate: 0.45,
      trailBackgroundDiffuseRate: 8.7,
    },
  },
  {
    name: "Rainbow",
    presetType: "Color Only",
    isBasePreset: true,
    colorSettings: {
      backgroundColor: "#130f26",
      slimeColorMode: "Procedural",
      proceduralColorPalette: {
        r: { yOffset: 0.5, amplitude: 0.5, frequency: 1.0, phase: 0.0 },
        g: { yOffset: 0.5, amplitude: 0.5, frequency: 1.0, phase: 0.33 },
        b: { yOffset: 0.5, amplitude: 0.5, frequency: 1.0, phase: 0.66 },
      },
      intensitySmoothing: 0.59,
      agentDirectionSmoothing: 0.68,
      agentDirectionColorOffset: 0.42,
      clockColorOffset: 0.64,
      xColorOffset: 0.65,
      yColorOffset: 0.8,
      paletteCycleSpeed: 0.54,
      paletteCycleScale: 0.1,
      paletteCycleType: 1,
    },
  },
  {
    name: "Pride 01",
    presetType: "Color Only",
    isBasePreset: true,
    colorSettings: {
      backgroundColor: "#510c43",
      slimeColorMode: "Procedural",
      proceduralColorPalette: {
        r: { yOffset: 0.52, amplitude: 0.46, frequency: 1.0, phase: 0.78 },
        g: { yOffset: 0.14, amplitude: 0.07, frequency: 1.0, phase: 0.33 },
        b: { yOffset: 0.74, amplitude: 0.16, frequency: 1.0, phase: 0.2 },
      },
      intensitySmoothing: 0.59,
      agentDirectionSmoothing: 0.68,
      agentDirectionColorOffset: 0.42,
      clockColorOffset: 0.64,
      xColorOffset: 0.65,
      yColorOffset: 0.8,
      paletteCycleSpeed: 0.54,
      paletteCycleScale: 0.1,
      paletteCycleType: 1,
    },
  },
  {
    name: "Unnamed Sim. 02", // Checked. TODO: Tweak it a little so it covers the digits better.
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.07,
      agentClockDepositRate: 6.4,
      agentBackgroundDepositRate: 8.3,
      agentSensorDegrees: 24,
      agentRotationRate: 4,
      agentSensorOffset: 12,
      agentSensorWidth: 3,
      agentStepSize: 12,
      agentCrowdAvoidance: 0.17,
      agentWanderStrength: 4.1,
      trailClockDecayRate: 0.04,
      trailClockDiffuseRate: 9.9,
      trailBackgroundDecayRate: 0.39,
      trailBackgroundDiffuseRate: 11.2,
    },
  },
  {
    name: "Unnamed Sim. 03", // Checked. TODO: Tweak it to fill the digits better
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 2.7,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.72,
      agentClockDepositRate: 14.8,
      agentBackgroundDepositRate: 5,
      agentSensorDegrees: 31,
      agentRotationRate: 3.1,
      agentSensorOffset: 5,
      agentSensorWidth: 1,
      agentStepSize: 6,
      agentCrowdAvoidance: 0.5,
      agentWanderStrength: 3.8,
      trailClockDecayRate: 0.49,
      trailClockDiffuseRate: 8.6,
      trailBackgroundDecayRate: 0.56,
      trailBackgroundDiffuseRate: 7.8,
    },
  },
  {
    name: "Unnamed Sim. 06 (Possibly 'Inverted 02')", // Checked
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.23,
      agentClockDepositRate: 7.8,
      agentBackgroundDepositRate: 18.2,
      agentSensorDegrees: 43,
      agentRotationRate: 1.1,
      agentSensorOffset: 10,
      agentSensorWidth: 1,
      agentStepSize: 8,
      agentCrowdAvoidance: 0.27,
      agentWanderStrength: 1.6,
      trailClockDecayRate: 0.29,
      trailClockDiffuseRate: 7.2,
      trailBackgroundDecayRate: 0.11,
      trailBackgroundDiffuseRate: 3.8,
    },
  },
  {
    name: "Unnamed Sim. 07 (Possibly 'Inverted 03')", // Checked
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.69,
      agentClockDepositRate: 4,
      agentBackgroundDepositRate: 12.2,
      agentSensorDegrees: 66,
      agentRotationRate: 7.2,
      agentSensorOffset: 13,
      agentSensorWidth: 5,
      agentStepSize: 18,
      agentCrowdAvoidance: 0.46,
      agentWanderStrength: 1.4,
      trailClockDecayRate: 0.47,
      trailClockDiffuseRate: 3,
      trailBackgroundDecayRate: 0.19,
      trailBackgroundDiffuseRate: 6.4,
    },
  },
  {
    name: "Unnamed Sim. 08 (Possibly 'Spectral')", // Checked. TODO: Keeping because it's interesting, but it needs work.
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.17,
      agentClockDepositRate: 16.6,
      agentBackgroundDepositRate: 6.9,
      agentSensorDegrees: 41,
      agentRotationRate: 5.1,
      agentSensorOffset: 3,
      agentSensorWidth: 4,
      agentStepSize: 18,
      agentCrowdAvoidance: 0.26,
      agentWanderStrength: 6.6,
      trailClockDecayRate: 0.28,
      trailClockDiffuseRate: 14.3,
      trailBackgroundDecayRate: 0.72,
      trailBackgroundDiffuseRate: 5.1,
    },
  },
  {
    name: "Unnamed Sim. 09 (Possibly 'Spiderwebby')", // Checked
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.65,
      agentClockDepositRate: 18.9,
      agentBackgroundDepositRate: 11.5,
      agentSensorDegrees: 15,
      agentRotationRate: 5,
      agentSensorOffset: 11,
      agentSensorWidth: 2,
      agentStepSize: 10,
      agentCrowdAvoidance: 0.33,
      agentWanderStrength: 4.4,
      trailClockDecayRate: 0.29,
      trailClockDiffuseRate: 9.9,
      trailBackgroundDecayRate: 0.69,
      trailBackgroundDiffuseRate: 2.1,
    },
  },
  {
    name: "Unnamed Sim. 10 (Possibly 'Slimy 07')", // Checked
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 1,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.04,
      agentClockDepositRate: 8.3,
      agentBackgroundDepositRate: 7.3,
      agentSensorDegrees: 21,
      agentRotationRate: 3,
      agentSensorOffset: 11,
      agentSensorWidth: 2,
      agentStepSize: 13,
      agentCrowdAvoidance: 0.2,
      agentWanderStrength: 6.5,
      trailClockDecayRate: 0.05,
      trailClockDiffuseRate: 7.8,
      trailBackgroundDecayRate: 0.48,
      trailBackgroundDiffuseRate: 10.6,
    },
  },
  {
    name: "Unnamed Color 01",
    presetType: "Color Only",
    isBasePreset: true,
    colorSettings: {
      backgroundColor: "#e9f8be",
      slimeColorMode: "Procedural",
      proceduralColorPalette: {
        r: {
          yOffset: 0.52,
          amplitude: 0.66,
          frequency: 1.33,
          phase: 1.84,
        },
        g: {
          yOffset: 0.21,
          amplitude: 0.4,
          frequency: 0.99,
          phase: 0.93,
        },
        b: {
          yOffset: 0.32,
          amplitude: 0.75,
          frequency: 1.22,
          phase: 0.9,
        },
      },
      intensitySmoothing: 0.59,
      agentDirectionSmoothing: 0.68,
      agentDirectionColorOffset: 0.42,
      clockColorOffset: 0.64,
      xColorOffset: 0.65,
      yColorOffset: 0.8,
      paletteCycleSpeed: 0.54,
      paletteCycleScale: 0.1,
      paletteCycleType: 1,
    },
  },
  {
    name: "Unnamed Color 02",
    presetType: "Color Only",
    isBasePreset: true,
    colorSettings: {
      backgroundColor: "#1b7d34",
      slimeColorMode: "Procedural",
      proceduralColorPalette: {
        r: {
          yOffset: 0.49,
          amplitude: 0.66,
          frequency: 1.18,
          phase: 2.41,
        },
        g: {
          yOffset: 0.67,
          amplitude: 0.71,
          frequency: 0.7,
          phase: 1.17,
        },
        b: {
          yOffset: 0.4,
          amplitude: 0.61,
          frequency: 1.33,
          phase: 0.81,
        },
      },
      intensitySmoothing: 0.59,
      agentDirectionSmoothing: 0.68,
      agentDirectionColorOffset: 0.42,
      clockColorOffset: 0.64,
      xColorOffset: 0.65,
      yColorOffset: 0.8,
      paletteCycleSpeed: 0.54,
      paletteCycleScale: 0.1,
      paletteCycleType: 1,
    },
  },
  {
    name: "Unnamed Color 03",
    presetType: "Color Only",
    isBasePreset: true,
    colorSettings: {
      backgroundColor: "#000000",
      slimeColorMode: "Procedural",
      proceduralColorPalette: {
        r: {
          yOffset: 0.5,
          amplitude: 0.45,
          frequency: 1.12,
          phase: 1.14,
        },
        g: {
          yOffset: 0.88,
          amplitude: 0.49,
          frequency: 0.42,
          phase: 2.13,
        },
        b: {
          yOffset: 0.8,
          amplitude: 0.46,
          frequency: 1.39,
          phase: 1.55,
        },
      },
      intensitySmoothing: 0.94,
      agentDirectionSmoothing: 0.93,
      agentDirectionColorOffset: 0.12,
      clockColorOffset: 0.07,
      xColorOffset: -0.35,
      yColorOffset: 0.8,
      paletteCycleSpeed: 0.54,
      paletteCycleScale: 0.06,
      paletteCycleType: 0,
    },
  },
  {
    name: "Pride 02",
    presetType: "Color Only",
    isBasePreset: true,
    colorSettings: {
      backgroundColor: "#ffffff",
      slimeColorMode: "Procedural",
      proceduralColorPalette: {
        r: {
          yOffset: 1,
          amplitude: 2,
          frequency: 1,
          phase: 0.5,
        },
        g: {
          yOffset: 0.75,
          amplitude: 0.28,
          frequency: 2,
          phase: 0,
        },
        b: {
          yOffset: 1,
          amplitude: 0.31,
          frequency: 2,
          phase: 0,
        },
      },
      intensitySmoothing: 0.59,
      agentDirectionSmoothing: 0.68,
      agentDirectionColorOffset: -0.17,
      clockColorOffset: 0.64,
      xColorOffset: -0.24,
      yColorOffset: 0.24,
      paletteCycleSpeed: 0.4,
      paletteCycleScale: 0.1,
      paletteCycleType: 1,
    },
  },
  {
    name: "Black & White",
    presetType: "Color Only",
    isBasePreset: true,
    colorSettings: {
      backgroundColor: "#000000",
      slimeColorMode: "Procedural",
      proceduralColorPalette: {
        r: {
          yOffset: 0.98,
          amplitude: 0.01,
          frequency: 1.33,
          phase: 1.27,
        },
        g: {
          yOffset: 0.98,
          amplitude: 0.01,
          frequency: 0.31,
          phase: 1.14,
        },
        b: {
          yOffset: 0.99,
          amplitude: 0.01,
          frequency: 0.94,
          phase: 0.31,
        },
      },
      intensitySmoothing: 0.59,
      agentDirectionSmoothing: 0.68,
      agentDirectionColorOffset: -0.01,
      clockColorOffset: 0.64,
      xColorOffset: 0.39,
      yColorOffset: -0.03,
      paletteCycleSpeed: 0.46,
      paletteCycleScale: 0.1,
      paletteCycleType: 1,
    },
  },
  {
    name: "White & Black",
    presetType: "Color Only",
    isBasePreset: true,
    colorSettings: {
      backgroundColor: "#ffffff",
      slimeColorMode: "Procedural",
      proceduralColorPalette: {
        r: {
          yOffset: 0.02,
          amplitude: 0.01,
          frequency: 1.33,
          phase: 1.27,
        },
        g: {
          yOffset: 0.02,
          amplitude: 0.01,
          frequency: 0.31,
          phase: 1.14,
        },
        b: {
          yOffset: 0.02,
          amplitude: 0.01,
          frequency: 0.94,
          phase: 0.31,
        },
      },
      intensitySmoothing: 0.59,
      agentDirectionSmoothing: 0.68,
      agentDirectionColorOffset: -0.01,
      clockColorOffset: 0.64,
      xColorOffset: 0.39,
      yColorOffset: -0.03,
      paletteCycleSpeed: 0.46,
      paletteCycleScale: 0.1,
      paletteCycleType: 1,
    },
  },
  {
    name: "Blue & Orange",
    presetType: "Color Only",
    isBasePreset: true,
    colorSettings: {
      backgroundColor: "#bcc2ff",
      slimeColorMode: "Procedural",
      proceduralColorPalette: {
        r: {
          yOffset: 0.22,
          amplitude: 1.25,
          frequency: 1,
          phase: 0,
        },
        g: {
          yOffset: 0.64,
          amplitude: 0.41,
          frequency: 1,
          phase: 0.5,
        },
        b: {
          yOffset: 0.82,
          amplitude: 1.09,
          frequency: 1,
          phase: 0.5,
        },
      },
      intensitySmoothing: 0.59,
      agentDirectionSmoothing: 0.68,
      agentDirectionColorOffset: 0.42,
      clockColorOffset: 0.64,
      xColorOffset: 0.65,
      yColorOffset: 0.8,
      paletteCycleSpeed: 0.54,
      paletteCycleScale: 0.1,
      paletteCycleType: 1,
    },
  },
  {
    name: "Black & Yellow",
    presetType: "Color Only",
    isBasePreset: true,
    colorSettings: {
      backgroundColor: "#ead600",
      slimeColorMode: "Procedural",
      proceduralColorPalette: {
        r: {
          yOffset: 0,
          amplitude: 0.43,
          frequency: 1,
          phase: 0,
        },
        g: {
          yOffset: 0,
          amplitude: 0.2,
          frequency: 1,
          phase: 0,
        },
        b: {
          yOffset: 0.04,
          amplitude: 0.01,
          frequency: 4,
          phase: 0.5,
        },
      },
      intensitySmoothing: 0.59,
      agentDirectionSmoothing: 0.68,
      agentDirectionColorOffset: 0.42,
      clockColorOffset: 0.64,
      xColorOffset: 0.65,
      yColorOffset: 0.8,
      paletteCycleSpeed: 0.54,
      paletteCycleScale: 0.1,
      paletteCycleType: 1,
    },
  },
];
export const SINGLE_PRESET_TYPES: SingleSimulationPresetType[] = [
  "Clock Only",
  "Simulation Only",
  "Color Only",
];
export const MULTIPLE_PRESET_TYPES: MultipleSimulationPresetType[] = [
  "Combination",
];
