import type {
  AgentStartTypeDropdownOption,
  ClockSettings,
  ColorRandomizationSettings,
  ColorSettings,
  DisplayTextureAspectRatioDropdownOption,
  LoadableClockSettings,
  LoadableColorSettings,
  LoadableSimulationSettings,
  LoadableSlimeStoreSettings,
  MultipleSimulationPresetType,
  NumericRangeRandomizationSetting,
  PaletteCycleTypeOption,
  ProceduralColorPaletteChannel,
  RandomizationPreset,
  SimulationSettings,
  SingleSimulationPresetType,
} from "../types/types";

type ControlsConfigs<T> = {
  [K in keyof T]?: { min: T[K]; max: T[K]; step: number };
};

export const DEFAULT_CLOCK_SETTINGS: ClockSettings = {
  show: true,
  size: 50,
  digitLayout: "not set",
  hourFormat: "24h",
  digitStyle: "roboto",
  padHours: true,
  showClockShadow: true,
  clockShadowOpacity: 0.1,
  clockShadowColor: "#6f6f6f",
};
export const CLOCK_CONTROLS_CONFIGS: ControlsConfigs<ClockSettings> = {
  size: { min: 1, max: 100, step: 1 },
  clockShadowOpacity: { min: 0, max: 1, step: 0.01 },
};

export const DEFAULT_SIMULATION_SETTINGS_PRESET_NAME = "Slimy 01";
// TODO: Replace the values in DEFAULT_SIMULATION_SETTINGS that get set
// by the `InitializationHandler` component with some sort of easily-identifiable
// placeholder values (like -1 or -999 or something). Consider commenting on these
// values too so you don't have to keep looking them up.
export const DEFAULT_SIMULATION_SETTINGS: SimulationSettings = {
  settingsSetPreviously: false,

  speed: 3.3,

  boundaryBehavior: 0, // 0: Wrap, 1: Bounce

  agentDensity: 0.25,
  gpuTextureWidth: 16,
  gpuTextureHeight: 16,
  agentStartType: -1,
  agentClockAttraction: 0.05,
  agentClockDepositRate: 6.5,
  agentBackgroundDepositRate: 6.5,
  agentSensorDegrees: 25,
  agentRotationRate: 2.2,
  agentSensorOffset: 1.85,
  agentSensorWidth: 0.42,
  agentStepSize: 1.52,
  agentCrowdAvoidance: 0.1,
  agentWanderStrength: 5.3,

  displayTextureAspectRatio: "Window",
  displayTextureTargetQuality: 1.0,
  displayTextureWidth: -1,
  displayTextureHeight: -1,
  trailClockDecayRate: 0.05,
  trailClockDiffuseRate: 4.5,
  trailBackgroundDecayRate: 0.39,
  trailBackgroundDiffuseRate: 11.7,

  showTextureDisplayPlanes: true,
};

export const SIMULATION_CONTROLS_CONFIGS: ControlsConfigs<SimulationSettings> =
  {
    speed: { min: 0.1, max: 10, step: 0.1 },

    agentClockAttraction: { min: 0.0, max: 1.0, step: 0.01 },
    agentClockDepositRate: { min: 0.0, max: 30.0, step: 0.1 },
    agentBackgroundDepositRate: { min: 0.0, max: 30.0, step: 0.1 },
    agentSensorDegrees: { min: 0.0, max: 180.0, step: 1.0 },
    agentRotationRate: { min: 0.0, max: 10.0, step: 0.1 },
    agentSensorOffset: { min: 0.0, max: 30.0, step: 0.01 },
    agentSensorWidth: { min: 0.0, max: 30.0, step: 0.01 },
    agentStepSize: { min: 0.0, max: 30.0, step: 0.01 },
    agentCrowdAvoidance: { min: 0.0, max: 1.0, step: 0.01 },
    agentWanderStrength: { min: 0.0, max: 20.0, step: 0.1 },

    displayTextureTargetQuality: { min: 0.1, max: 10.0, step: 0.1 },
    trailClockDecayRate: { min: 0.0, max: 2.0, step: 0.01 },
    trailClockDiffuseRate: { min: 0.0, max: 30.0, step: 0.1 },
    trailBackgroundDecayRate: { min: 0.0, max: 2.0, step: 0.01 },
    trailBackgroundDiffuseRate: { min: 0.0, max: 30.0, step: 0.1 },
  };

export const AGENT_START_TYPE_DROPDOWN_OPTIONS: AgentStartTypeDropdownOption[] =
  [
    { value: "-1", label: "Random" },
    { value: "0", label: "Center" },
    { value: "1", label: "Ring" },
    { value: "2", label: "9 Rings" },
    { value: "3", label: "Circle" },
    { value: "4", label: "Spiral" },
    { value: "5", label: "Fill" },
    { value: "6", label: "Hexagonal Grid" },
  ] as const;

export const RANDOMIZATION_SETTINGS_AGENT_START_TYPE_OPTIONS: Record<
  string,
  { enabled: boolean; value: string; label: string }
> = AGENT_START_TYPE_DROPDOWN_OPTIONS.reduce(
  (acc, option) => {
    if (option.label === "Random") return acc;
    acc[option.label] = { ...option, enabled: true };
    return acc;
  },
  {} as Record<string, { enabled: boolean; value: string; label: string }>,
);

const DEFAULT_PROCEDURAL_COLOR_PALETTE_RANDOMIZATION_SETTINGS: {
  yOffset: NumericRangeRandomizationSetting;
  amplitude: NumericRangeRandomizationSetting;
  frequency: NumericRangeRandomizationSetting;
  phase: NumericRangeRandomizationSetting;
} = {
  yOffset: {
    type: "numericRange",
    enabled: true,
    flatRange: [0.0, 1.0],
    mu: 0.5,
    sigma: 0.15,
    mode: "gaussian",
  },
  amplitude: {
    type: "numericRange",
    enabled: true,
    flatRange: [0.05, 0.95],
    mu: 0.5,
    sigma: 0.15,
    mode: "gaussian",
  },
  frequency: {
    type: "numericRange",
    enabled: true,
    flatRange: [0.1, 3.0],
    mu: 1.0,
    sigma: 0.3,
    mode: "gaussian",
  },
  phase: {
    type: "numericRange",
    enabled: true,
    flatRange: [0.0, 3.14],
    mu: 1.57,
    sigma: 0.5,
    mode: "gaussian",
  },
};
export const DEFAULT_COLOR_RANDOMIZATION_SETTINGS: ColorRandomizationSettings =
  {
    backgroundColor: { type: "color", enabled: true },
    proceduralColorPalette: {
      r: DEFAULT_PROCEDURAL_COLOR_PALETTE_RANDOMIZATION_SETTINGS,
      g: DEFAULT_PROCEDURAL_COLOR_PALETTE_RANDOMIZATION_SETTINGS,
      b: DEFAULT_PROCEDURAL_COLOR_PALETTE_RANDOMIZATION_SETTINGS,
    },
    intensitySmoothing: {
      type: "numericRange",
      enabled: false,
      flatRange: [0.4, 0.6],
      mu: 0.5,
      sigma: 0.03,
      mode: "gaussian",
    },
    agentDirectionSmoothing: {
      type: "numericRange",
      enabled: false,
      flatRange: [0.4, 0.6],
      mu: 0.5,
      sigma: 0.03,
      mode: "gaussian",
    },
    agentDirectionColorOffset: {
      type: "numericRange",
      enabled: true,
      flatRange: [-0.2, 0.2],
      mu: 0.0,
      sigma: 0.1,
      mode: "gaussian",
    },
    clockColorOffset: {
      type: "numericRange",
      enabled: false,
      flatRange: [0.05, 0.25],
      mu: 0.15,
      sigma: 0.03,
      mode: "gaussian",
    },
    xColorOffset: {
      type: "numericRange",
      enabled: true,
      flatRange: [-0.5, 0.5],
      mu: 0.0,
      sigma: 0.9,
      mode: "gaussian",
    },
    yColorOffset: {
      type: "numericRange",
      enabled: true,
      flatRange: [-0.5, 0.5],
      mu: 0.0,
      sigma: 0.9,
      mode: "gaussian",
    },
    paletteCycleSpeed: {
      type: "numericRange",
      enabled: true,
      flatRange: [0.2, 0.8],
      mu: 0.5,
      sigma: 0.15,
      mode: "gaussian",
    },
    paletteCycleScale: {
      type: "numericRange",
      enabled: false,
      flatRange: [0.05, 0.25],
      mu: 0.15,
      sigma: 0.03,
      mode: "gaussian",
    },
  };

export const DEFAULT_SIMULATION_RANDOMIZATION_SETTINGS_PRESET_NAME =
  "Test Slime";
export const DEFAULT_COLOR_RANDOMIZATION_SETTINGS_PRESET_NAME = "Colorful";
export const RANDOMIZATION_PRESETS: RandomizationPreset[] = [
  {
    presetType: "simulation",
    name: "Test Slime",
    isBasePreset: true,
    enabled: true,
    settings: {
      agentStartType: {
        type: "optionList",
        enabled: true,
        options: { ...RANDOMIZATION_SETTINGS_AGENT_START_TYPE_OPTIONS },
      },
      agentClockAttraction: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.02, 0.07],
        mu: 0.05,
        sigma: 0.03,
        mode: "gaussian",
      },
      agentClockDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2.0, 15.0],
        mu: 8.0,
        sigma: 3.0,
        mode: "gaussian",
      },
      agentBackgroundDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2.0, 15.0],
        mu: 8.0,
        sigma: 3.0,
        mode: "gaussian",
      },
      agentSensorDegrees: {
        type: "numericRange",
        enabled: true,
        flatRange: [15, 75],
        mu: 25.0,
        sigma: 5.0,
        mode: "gaussian",
      },
      agentRotationRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [1.0, 5.0],
        mu: 3.0,
        sigma: 0.75,
        mode: "gaussian",
      },
      agentSensorOffset: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.5, 2.5],
        mu: 1.2,
        sigma: 0.3,
        mode: "gaussian",
      },
      agentSensorWidth: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.2, 0.8],
        mu: 0.3,
        sigma: 0.1,
        mode: "gaussian",
      },
      agentStepSize: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.5, 2.5],
        mu: 1.2,
        sigma: 0.3,
        mode: "gaussian",
      },
      agentCrowdAvoidance: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.05, 0.5],
        mu: 0.15,
        sigma: 0.08,
        mode: "gaussian",
      },
      agentWanderStrength: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.1, 10.0],
        mu: 5.0,
        sigma: 1.5,
        mode: "gaussian",
      },

      trailClockDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.01, 0.5],
        mu: 0.1,
        sigma: 0.1,
        mode: "gaussian",
      },
      trailClockDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2.0, 10.0],
        mu: 8,
        sigma: 2.5,
        mode: "gaussian",
      },
      trailBackgroundDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.01, 0.5],
        mu: 0.5,
        sigma: 0.1,
        mode: "gaussian",
      },
      trailBackgroundDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2.0, 15.0],
        mu: 8.0,
        sigma: 2.5,
        mode: "gaussian",
      },
    },
  },
  {
    presetType: "simulation",
    name: "Speedy Slime",
    isBasePreset: true,
    enabled: true,
    settings: {
      agentStartType: {
        type: "optionList",
        enabled: true,
        options: { ...RANDOMIZATION_SETTINGS_AGENT_START_TYPE_OPTIONS },
      },
      agentClockAttraction: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.03, 0.06],
        mu: 0.05,
        sigma: 0.02,
        mode: "gaussian",
      },
      agentClockDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2.0, 15.0],
        mu: 8.0,
        sigma: 1.5,
        mode: "gaussian",
      },
      agentBackgroundDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2.0, 15.0],
        mu: 8.0,
        sigma: 1.5,
        mode: "gaussian",
      },
      agentSensorDegrees: {
        type: "numericRange",
        enabled: true,
        flatRange: [15, 75],
        mu: 25,
        sigma: 3,
        mode: "gaussian",
      },
      agentRotationRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [1.0, 5.0],
        mu: 3,
        sigma: 0.75,
        mode: "gaussian",
      },
      agentSensorOffset: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.5, 2.5],
        mu: 1.0,
        sigma: 0.2,
        mode: "gaussian",
      },
      agentSensorWidth: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.2, 0.8],
        mu: 0.3,
        sigma: 0.05,
        mode: "gaussian",
      },
      agentStepSize: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.5, 2.5],
        mu: 1.0,
        sigma: 0.2,
        mode: "gaussian",
      },
      agentCrowdAvoidance: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.05, 0.5],
        mu: 0.22,
        sigma: 0.08,
        mode: "gaussian",
      },
      agentWanderStrength: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.1, 10.0],
        mu: 6.5,
        sigma: 1.3,
        mode: "gaussian",
      },

      trailClockDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.01, 0.5],
        mu: 0.1,
        sigma: 0.1,
        mode: "gaussian",
      },
      trailClockDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2.0, 10.0],
        mu: 8,
        sigma: 1.3,
        mode: "gaussian",
      },
      trailBackgroundDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.01, 0.5],
        mu: 0.45,
        sigma: 0.1,
        mode: "gaussian",
      },
      trailBackgroundDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [2.0, 15.0],
        mu: 10.5,
        sigma: 1.5,
        mode: "gaussian",
      },
    },
  },
  {
    presetType: "simulation",
    name: "Slow Slime",
    isBasePreset: true,
    enabled: true,
    settings: {
      agentStartType: {
        type: "optionList",
        enabled: true,
        options: { ...RANDOMIZATION_SETTINGS_AGENT_START_TYPE_OPTIONS },
      },
      agentClockAttraction: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.6, 0.8],
        mu: 0.7,
        sigma: 0.03,
        mode: "gaussian",
      },
      agentClockDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [12.0, 16.0],
        mu: 14.0,
        sigma: 1.0,
        mode: "gaussian",
      },
      agentBackgroundDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [4.0, 6.0],
        mu: 5.0,
        sigma: 0.3,
        mode: "gaussian",
      },
      agentSensorDegrees: {
        type: "numericRange",
        enabled: true,
        flatRange: [15, 35],
        mu: 25,
        sigma: 3,
        mode: "gaussian",
      },
      agentRotationRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [1.3, 4.3],
        mu: 2.8,
        sigma: 0.5,
        mode: "gaussian",
      },
      agentSensorOffset: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.4, 0.7],
        mu: 0.55,
        sigma: 0.05,
        mode: "gaussian",
      },
      agentSensorWidth: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.1, 0.2],
        mu: 0.15,
        sigma: 0.02,
        mode: "gaussian",
      },
      agentStepSize: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.4, 0.7],
        mu: 0.55,
        sigma: 0.05,
        mode: "gaussian",
      },
      agentCrowdAvoidance: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.2, 0.5],
        mu: 0.35,
        sigma: 0.1,
        mode: "gaussian",
      },
      agentWanderStrength: {
        type: "numericRange",
        enabled: true,
        flatRange: [3.0, 7.0],
        mu: 5.0,
        sigma: 1.0,
        mode: "gaussian",
      },

      trailClockDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.35, 0.55],
        mu: 0.45,
        sigma: 0.06,
        mode: "gaussian",
      },
      trailClockDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [7.0, 10.0],
        mu: 8.5,
        sigma: 0.7,
        mode: "gaussian",
      },
      trailBackgroundDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.35, 0.55],
        mu: 0.45,
        sigma: 0.06,
        mode: "gaussian",
      },
      trailBackgroundDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [7.0, 10.0],
        mu: 8.5,
        sigma: 0.7,
        mode: "gaussian",
      },
    },
  },
  {
    presetType: "simulation",
    name: "Inverted",
    enabled: true,
    isBasePreset: true,
    settings: {
      agentStartType: {
        type: "optionList",
        enabled: true,
        options: {
          Center: {
            value: "0",
            label: "Center",
            enabled: true,
          },
          Ring: {
            value: "1",
            label: "Ring",
            enabled: true,
          },
          "9 Rings": {
            value: "2",
            label: "9 Rings",
            enabled: true,
          },
          Circle: {
            value: "3",
            label: "Circle",
            enabled: false,
          },
          Spiral: {
            value: "4",
            label: "Spiral",
            enabled: true,
          },
          Fill: {
            value: "5",
            label: "Fill",
            enabled: false,
          },
        },
      },
      agentClockAttraction: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.6, 0.8],
        mu: 0.7,
        sigma: 0.07,
        mode: "gaussian",
      },
      agentClockDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [12, 16],
        mu: 3,
        sigma: 0.5,
        mode: "gaussian",
      },
      agentBackgroundDepositRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [4, 6],
        mu: 12,
        sigma: 1,
        mode: "gaussian",
      },
      agentSensorDegrees: {
        type: "numericRange",
        enabled: true,
        flatRange: [15, 35],
        mu: 55,
        sigma: 6,
        mode: "gaussian",
      },
      agentRotationRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [1.3, 4.3],
        mu: 7,
        sigma: 0.5,
        mode: "gaussian",
      },
      agentSensorOffset: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.4, 0.7],
        mu: 0.9,
        sigma: 0.15,
        mode: "gaussian",
      },
      agentSensorWidth: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.1, 0.2],
        mu: 0.42,
        sigma: 0.1,
        mode: "gaussian",
      },
      agentStepSize: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.4, 0.7],
        mu: 0.9,
        sigma: 0.15,
        mode: "gaussian",
      },
      agentCrowdAvoidance: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.2, 0.5],
        mu: 0.45,
        sigma: 0.1,
        mode: "gaussian",
      },
      agentWanderStrength: {
        type: "numericRange",
        enabled: true,
        flatRange: [3, 7],
        mu: 1.5,
        sigma: 0.5,
        mode: "gaussian",
      },
      trailClockDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.35, 0.55],
        mu: 0.5,
        sigma: 0.1,
        mode: "gaussian",
      },
      trailClockDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [7, 10],
        mu: 3,
        sigma: 0.3,
        mode: "gaussian",
      },
      trailBackgroundDecayRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [0.35, 0.55],
        mu: 0.2,
        sigma: 0.06,
        mode: "gaussian",
      },
      trailBackgroundDiffuseRate: {
        type: "numericRange",
        enabled: true,
        flatRange: [7, 10],
        mu: 6.5,
        sigma: 1,
        mode: "gaussian",
      },
    },
  },
  {
    presetType: "color",
    name: "Colorful",
    isBasePreset: true,
    enabled: true,
    settings: {
      ...DEFAULT_COLOR_RANDOMIZATION_SETTINGS,
    },
  },
];

export const DEFAULT_COLOR_SETTINGS_PRESET_NAME = "Rainbow";
export const DEFAULT_COLOR_SETTINGS: ColorSettings = {
  settingsSetPreviously: false,
  slimeColorChangedAt: 0,

  backgroundColor: "#70f3eb",
  slimeColorMode: "Procedural",
  proceduralColorPalette: {
    r: { yOffset: 0.5, amplitude: 0.5, frequency: 1.0, phase: 0.0 },
    g: { yOffset: 0.5, amplitude: 0.5, frequency: 1.0, phase: 0.33 },
    b: { yOffset: 0.5, amplitude: 0.5, frequency: 1.0, phase: 0.66 },
  },
  intensitySmoothing: 0.59,
  agentDirectionSmoothing: 0.68,
  agentDirectionColorOffset: 0.42,
  clockColorOffset: 0.64,
  xColorOffset: 0.65,
  yColorOffset: 0.8,
  paletteCycleSpeed: 0.54,
  paletteCycleScale: 0.1,
  paletteCycleType: 1,
};

export const COLOR_CONTROLS_CONFIGS: ControlsConfigs<ColorSettings> = {
  intensitySmoothing: { min: 0.0, max: 1.0, step: 0.01 },
  agentDirectionSmoothing: { min: 0.0, max: 1.0, step: 0.01 },
  agentDirectionColorOffset: { min: -1.0, max: 1.0, step: 0.01 },
  clockColorOffset: { min: -1.0, max: 1.0, step: 0.01 },
  xColorOffset: { min: -1.0, max: 1.0, step: 0.01 },
  yColorOffset: { min: -1.0, max: 1.0, step: 0.01 },
  paletteCycleSpeed: { min: 0.0, max: 1.0, step: 0.01 },
  paletteCycleScale: { min: 0.01, max: 1.0, step: 0.01 },
};

export const PROCEDURAL_COLOR_PALETTE_CONTROLS_CONFIGS: ControlsConfigs<ProceduralColorPaletteChannel> =
  {
    yOffset: { min: 0.0, max: 1.0, step: 0.01 },
    amplitude: { min: 0.0, max: 5.0, step: 0.01 },
    frequency: { min: 0.0, max: 5.0, step: 0.01 },
    phase: {
      min: 0.0,
      max: Math.round(Math.PI * 100) / 100,
      step: 0.01,
    },
  };

const flickerPoints = Array.from({ length: 11 }, (_, i) => i / 10);
const flickerInOpacity = flickerPoints.map((point) =>
  Math.min(
    1,
    Math.max(
      0,
      Math.sin(6 * Math.PI * point) * Math.sin(Math.PI * point) * 0.4 + point,
    ),
  ),
);

export const ANIMATION_CONFIGS = {
  flickerIn: {
    opacity: flickerInOpacity,
    transition: {
      duration: 0.3,
      times: flickerPoints,
      when: "beforeChildren",
    },
  },
  flickerOut: {
    opacity: flickerInOpacity.slice().reverse(),
    transition: {
      duration: 0.3,
      times: flickerPoints,
      when: "afterChildren",
    },
  },
};

export const DISPLAY_TEXTURE_ASPECT_RATIO_OPTIONS: DisplayTextureAspectRatioDropdownOption[] =
  [
    { value: "Window", label: "Window" },
    { value: "16:10", label: "16:10" },
    { value: "16:9", label: "16:9" },
    { value: "4:3", label: "4:3" },
    { value: "3:2", label: "3:2" },
    { value: "1:1", label: "1:1" },
    { value: "2:3", label: "2:3" },
    { value: "3:4", label: "3:4" },
    { value: "9:16", label: "9:16" },
    { value: "10:16", label: "10:16" },
  ] as const;

export const PALETTE_CYCLE_TYPE_OPTIONS: PaletteCycleTypeOption[] = [
  { value: "0", label: "Oscillating" },
  { value: "1", label: "Repeating" },
  { value: "2", label: "Continuous" },
] as const;

export const LOADABLE_CLOCK_SETTINGS_KEYS: (keyof LoadableClockSettings)[] = [
  "show",
  "size",
  "digitLayout",
  "hourFormat",
  "digitStyle",
  "padHours",
  "showClockShadow",
  "clockShadowOpacity",
  "clockShadowColor",
];
export const LOADABLE_SIMULATION_SETTINGS_KEYS: (keyof LoadableSimulationSettings)[] =
  [
    "speed",
    "boundaryBehavior",
    "agentDensity",
    "agentStartType",
    "agentClockAttraction",
    "agentClockDepositRate",
    "agentBackgroundDepositRate",
    "agentSensorDegrees",
    "agentRotationRate",
    "agentSensorOffset",
    "agentSensorWidth",
    "agentStepSize",
    "agentCrowdAvoidance",
    "agentWanderStrength",
    "trailClockDecayRate",
    "trailClockDiffuseRate",
    "trailBackgroundDecayRate",
    "trailBackgroundDiffuseRate",
  ];
export const LOADABLE_COLOR_SETTINGS_KEYS: (keyof LoadableColorSettings)[] = [
  "backgroundColor",
  "slimeColorMode",
  "proceduralColorPalette",
  "intensitySmoothing",
  "agentDirectionSmoothing",
  "agentDirectionColorOffset",
  "clockColorOffset",
  "xColorOffset",
  "yColorOffset",
  "paletteCycleSpeed",
  "paletteCycleScale",
  "paletteCycleType",
];

export const DEFAULT_PRESETS: LoadableSlimeStoreSettings[] = [
  {
    name: "Horizontal",
    presetType: "Clock Only",
    isBasePreset: true,
    clockSettings: {
      show: true,
      size: 50,
      digitLayout: "horizontal",
      hourFormat: "24h",
      digitStyle: "14segment",
      padHours: true,
      showClockShadow: true,
      clockShadowOpacity: 0.25,
      clockShadowColor: "#6f6f6f",
    },
  },
  {
    name: "Vertical",
    presetType: "Clock Only",
    isBasePreset: true,
    clockSettings: {
      show: true,
      size: 30,
      digitLayout: "vertical",
      hourFormat: "24h",
      digitStyle: "14segment",
      padHours: true,
      showClockShadow: true,
      clockShadowOpacity: 0.25,
      clockShadowColor: "#6f6f6f",
    },
  },
  {
    name: "Extra Gooey 01",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.2,
      agentClockDepositRate: 12.1,
      agentBackgroundDepositRate: 3.2,
      agentSensorDegrees: 52,
      agentRotationRate: 3.3,
      agentSensorOffset: 0.91,
      agentSensorWidth: 0.28,
      agentStepSize: 1.45,
      agentCrowdAvoidance: 0.16,
      agentWanderStrength: 9.6,
      trailClockDecayRate: 0.05,
      trailClockDiffuseRate: 5.2,
      trailBackgroundDecayRate: 0.07,
      trailBackgroundDiffuseRate: 4.9,
    },
  },
  {
    name: "Extra Gooey 02",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.11,
      agentClockDepositRate: 7.4,
      agentBackgroundDepositRate: 14.8,
      agentSensorDegrees: 60,
      agentRotationRate: 4.6,
      agentSensorOffset: 0.74,
      agentSensorWidth: 0.24,
      agentStepSize: 2.26,
      agentCrowdAvoidance: 0.47,
      agentWanderStrength: 2,
      trailClockDecayRate: 0.04,
      trailClockDiffuseRate: 5.7,
      trailBackgroundDecayRate: 0.39,
      trailBackgroundDiffuseRate: 3.7,
    },
  },
  {
    name: "Fuzzy 01",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.04,
      agentClockDepositRate: 11,
      agentBackgroundDepositRate: 12.6,
      agentSensorDegrees: 22,
      agentRotationRate: 2.7,
      agentSensorOffset: 2.43,
      agentSensorWidth: 0.35,
      agentStepSize: 1.34,
      agentCrowdAvoidance: 0.33,
      agentWanderStrength: 9.4,
      trailClockDecayRate: 0.02,
      trailClockDiffuseRate: 9.2,
      trailBackgroundDecayRate: 0.28,
      trailBackgroundDiffuseRate: 10.2,
    },
  },
  {
    name: "Inverted Roiling",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.2,
      agentClockDepositRate: 3.1,
      agentBackgroundDepositRate: 11.9,
      agentSensorDegrees: 24,
      agentRotationRate: 4.3,
      agentSensorOffset: 2.08,
      agentSensorWidth: 0.43,
      agentStepSize: 2.16,
      agentCrowdAvoidance: 0.37,
      agentWanderStrength: 3.8,
      trailClockDecayRate: 0.47,
      trailClockDiffuseRate: 2.4,
      trailBackgroundDecayRate: 0.07,
      trailBackgroundDiffuseRate: 9.9,
    },
  },
  {
    name: "Slimy 01",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.05,
      agentClockDepositRate: 6.5,
      agentBackgroundDepositRate: 6.5,
      agentSensorDegrees: 25,
      agentRotationRate: 2.2,
      agentSensorOffset: 1.85,
      agentSensorWidth: 0.42,
      agentStepSize: 1.52,
      agentCrowdAvoidance: 0.1,
      agentWanderStrength: 5.3,
      trailClockDecayRate: 0.05,
      trailClockDiffuseRate: 4.5,
      trailBackgroundDecayRate: 0.39,
      trailBackgroundDiffuseRate: 11.7,
    },
  },
  {
    name: "Slimy 02",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.18,
      agentClockDepositRate: 7.6,
      agentBackgroundDepositRate: 9.4,
      agentSensorDegrees: 17,
      agentRotationRate: 2.8,
      agentSensorOffset: 1.59,
      agentSensorWidth: 0.31,
      agentStepSize: 2.24,
      agentCrowdAvoidance: 0.41,
      agentWanderStrength: 0.4,
      trailClockDecayRate: 0.05,
      trailClockDiffuseRate: 5,
      trailBackgroundDecayRate: 0.41,
      trailBackgroundDiffuseRate: 12.9,
    },
  },
  {
    name: "Slimy 03",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.03,
      agentClockDepositRate: 14.5,
      agentBackgroundDepositRate: 5.9,
      agentSensorDegrees: 47,
      agentRotationRate: 1.5,
      agentSensorOffset: 2.22,
      agentSensorWidth: 0.41,
      agentStepSize: 1.33,
      agentCrowdAvoidance: 0.33,
      agentWanderStrength: 0.4,
      trailClockDecayRate: 0.01,
      trailClockDiffuseRate: 4.5,
      trailBackgroundDecayRate: 0.21,
      trailBackgroundDiffuseRate: 5.2,
    },
  },
  {
    name: "Slimy 04",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.07,
      agentClockDepositRate: 9.3,
      agentBackgroundDepositRate: 12.7,
      agentSensorDegrees: 72,
      agentRotationRate: 2.4,
      agentSensorOffset: 1.66,
      agentSensorWidth: 0.25,
      agentStepSize: 1.76,
      agentCrowdAvoidance: 0.17,
      agentWanderStrength: 1.1,
      trailClockDecayRate: 0.06,
      trailClockDiffuseRate: 4.3,
      trailBackgroundDecayRate: 0.43,
      trailBackgroundDiffuseRate: 2,
    },
  },
  {
    name: "Slimy 05",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.05,
      agentClockDepositRate: 10.2,
      agentBackgroundDepositRate: 12.2,
      agentSensorDegrees: 20,
      agentRotationRate: 3.2,
      agentSensorOffset: 1.05,
      agentSensorWidth: 0.3,
      agentStepSize: 2.17,
      agentCrowdAvoidance: 0.12,
      agentWanderStrength: 8,
      trailClockDecayRate: 0.08,
      trailClockDiffuseRate: 9.5,
      trailBackgroundDecayRate: 0.49,
      trailBackgroundDiffuseRate: 4.5,
    },
  },
  {
    name: "Slimy 06",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.27,
      agentClockDepositRate: 3.3,
      agentBackgroundDepositRate: 11,
      agentSensorDegrees: 47,
      agentRotationRate: 3.8,
      agentSensorOffset: 0.99,
      agentSensorWidth: 0.26,
      agentStepSize: 2.23,
      agentCrowdAvoidance: 0.3,
      agentWanderStrength: 4.6,
      trailClockDecayRate: 0.02,
      trailClockDiffuseRate: 3.5,
      trailBackgroundDecayRate: 0.45,
      trailBackgroundDiffuseRate: 8.7,
    },
  },
  {
    name: "Inverted Gooey",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.09,
      agentClockDepositRate: 5.6,
      agentBackgroundDepositRate: 2.5,
      agentSensorDegrees: 19,
      agentRotationRate: 2.3,
      agentSensorOffset: 1.77,
      agentSensorWidth: 0.52,
      agentStepSize: 2.34,
      agentCrowdAvoidance: 0.22,
      agentWanderStrength: 2.9,
      trailClockDecayRate: 0.28,
      trailClockDiffuseRate: 6.4,
      trailBackgroundDecayRate: 0.07,
      trailBackgroundDiffuseRate: 2.9,
    },
  },
  {
    name: "Rainbow",
    presetType: "Color Only",
    isBasePreset: true,
    colorSettings: {
      backgroundColor: "#70f3eb",
      slimeColorMode: "Procedural",
      proceduralColorPalette: {
        r: { yOffset: 0.5, amplitude: 0.5, frequency: 1.0, phase: 0.0 },
        g: { yOffset: 0.5, amplitude: 0.5, frequency: 1.0, phase: 0.33 },
        b: { yOffset: 0.5, amplitude: 0.5, frequency: 1.0, phase: 0.66 },
      },
      intensitySmoothing: 0.59,
      agentDirectionSmoothing: 0.68,
      agentDirectionColorOffset: 0.42,
      clockColorOffset: 0.64,
      xColorOffset: 0.65,
      yColorOffset: 0.8,
      paletteCycleSpeed: 0.54,
      paletteCycleScale: 0.1,
      paletteCycleType: 1,
    },
  },
  {
    name: "Bi",
    presetType: "Color Only",
    isBasePreset: true,
    colorSettings: {
      backgroundColor: "#510c43",
      slimeColorMode: "Procedural",
      proceduralColorPalette: {
        r: { yOffset: 0.52, amplitude: 0.46, frequency: 1.0, phase: 0.78 },
        g: { yOffset: 0.14, amplitude: 0.07, frequency: 1.0, phase: 0.33 },
        b: { yOffset: 0.74, amplitude: 0.16, frequency: 1.0, phase: 0.2 },
      },
      intensitySmoothing: 0.59,
      agentDirectionSmoothing: 0.68,
      agentDirectionColorOffset: 0.42,
      clockColorOffset: 0.64,
      xColorOffset: 0.65,
      yColorOffset: 0.8,
      paletteCycleSpeed: 0.54,
      paletteCycleScale: 0.1,
      paletteCycleType: 1,
    },
  },
  {
    name: "Supergoo",
    presetType: "Combination",
    isBasePreset: true,
    clockSettings: {
      show: true,
      size: 22,
      digitLayout: "vertical",
      hourFormat: "24h",
      digitStyle: "roboto",
      padHours: true,
      showClockShadow: true,
      clockShadowOpacity: 0.09,
      clockShadowColor: "#6f6f6f",
    },
    simulationSettings: {
      speed: 2.7,
      boundaryBehavior: 0,
      agentDensity: 0.3,
      agentStartType: -1,
      agentClockAttraction: 0.75,
      agentClockDepositRate: 14.5,
      agentBackgroundDepositRate: 5,
      agentSensorDegrees: 26,
      agentRotationRate: 2.8,
      agentSensorOffset: 0.56,
      agentSensorWidth: 0.14,
      agentStepSize: 0.5,
      agentCrowdAvoidance: 0.34,
      agentWanderStrength: 5.1,
      trailClockDecayRate: 0.45,
      trailClockDiffuseRate: 8.5,
      trailBackgroundDecayRate: 0.45,
      trailBackgroundDiffuseRate: 8.5,
    },
    colorSettings: {
      backgroundColor: "#000000",
      slimeColorMode: "Procedural",
      proceduralColorPalette: {
        r: {
          yOffset: 0.44,
          amplitude: 0.6,
          frequency: 0.98,
          phase: 0.98,
        },
        g: {
          yOffset: 0.39,
          amplitude: 0.38,
          frequency: 0.98,
          phase: 2.26,
        },
        b: {
          yOffset: 0.4,
          amplitude: 0.34,
          frequency: 1.17,
          phase: 1.5,
        },
      },
      intensitySmoothing: 0.94,
      agentDirectionSmoothing: 0.93,
      agentDirectionColorOffset: 0.12,
      clockColorOffset: 0.07,
      xColorOffset: -0.35,
      yColorOffset: 0.8,
      paletteCycleSpeed: 0.54,
      paletteCycleScale: 0.06,
      paletteCycleType: 0,
    },
  },

  // Need to check these & come up with names.
  {
    name: "Unnamed Sim. 01",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.08,
      agentClockDepositRate: 8.4,
      agentBackgroundDepositRate: 8,
      agentSensorDegrees: 26,
      agentRotationRate: 3.9,
      agentSensorOffset: 1.5,
      agentSensorWidth: 0.31,
      agentStepSize: 1.37,
      agentCrowdAvoidance: 0.17,
      agentWanderStrength: 5.8,
      trailClockDecayRate: 0.12,
      trailClockDiffuseRate: 8.4,
      trailBackgroundDecayRate: 0.49,
      trailBackgroundDiffuseRate: 9.6,
    },
  },
  {
    name: "Unnamed Sim. 02",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.07,
      agentClockDepositRate: 6.4,
      agentBackgroundDepositRate: 8.3,
      agentSensorDegrees: 24,
      agentRotationRate: 4,
      agentSensorOffset: 1.21,
      agentSensorWidth: 0.25,
      agentStepSize: 1.24,
      agentCrowdAvoidance: 0.17,
      agentWanderStrength: 4.1,
      trailClockDecayRate: 0.04,
      trailClockDiffuseRate: 9.9,
      trailBackgroundDecayRate: 0.39,
      trailBackgroundDiffuseRate: 11.2,
    },
  },
  {
    name: "Unnamed Sim. 03",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 2.7,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.72,
      agentClockDepositRate: 14.8,
      agentBackgroundDepositRate: 5,
      agentSensorDegrees: 31,
      agentRotationRate: 3.1,
      agentSensorOffset: 0.5,
      agentSensorWidth: 0.14,
      agentStepSize: 0.62,
      agentCrowdAvoidance: 0.5,
      agentWanderStrength: 3.8,
      trailClockDecayRate: 0.49,
      trailClockDiffuseRate: 8.6,
      trailBackgroundDecayRate: 0.56,
      trailBackgroundDiffuseRate: 7.8,
    },
  },
  {
    name: "Unnamed Sim. 04 (Possibly 'Fuzzy 02')",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.2,
      agentClockDepositRate: 18.4,
      agentBackgroundDepositRate: 14.7,
      agentSensorDegrees: 27,
      agentRotationRate: 1,
      agentSensorOffset: 0.28,
      agentSensorWidth: 0.48,
      agentStepSize: 1.13,
      agentCrowdAvoidance: 0.37,
      agentWanderStrength: 9,
      trailClockDecayRate: 0.14,
      trailClockDiffuseRate: 10.2,
      trailBackgroundDecayRate: 0.47,
      trailBackgroundDiffuseRate: 10.2,
    },
  },
  {
    name: "Unnamed Sim. 05 (Possibly 'Fuzzycrisp')",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.38,
      agentClockDepositRate: 13.5,
      agentBackgroundDepositRate: 10.8,
      agentSensorDegrees: 15,
      agentRotationRate: 1.5,
      agentSensorOffset: 0.52,
      agentSensorWidth: 0.28,
      agentStepSize: 2.77,
      agentCrowdAvoidance: 0.09,
      agentWanderStrength: 8.8,
      trailClockDecayRate: 0.08,
      trailClockDiffuseRate: 7.4,
      trailBackgroundDecayRate: 0.5,
      trailBackgroundDiffuseRate: 9.5,
    },
  },
  {
    name: "Unnamed Sim. 06 (Possibly 'Inverted 02')",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.23,
      agentClockDepositRate: 7.8,
      agentBackgroundDepositRate: 18.2,
      agentSensorDegrees: 43,
      agentRotationRate: 1.1,
      agentSensorOffset: 1.01,
      agentSensorWidth: 0.12,
      agentStepSize: 0.76,
      agentCrowdAvoidance: 0.27,
      agentWanderStrength: 1.6,
      trailClockDecayRate: 0.29,
      trailClockDiffuseRate: 7.2,
      trailBackgroundDecayRate: 0.11,
      trailBackgroundDiffuseRate: 3.8,
    },
  },
  {
    name: "Unnamed Sim. 07 (Possibly 'Inverted 03')",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.69,
      agentClockDepositRate: 4,
      agentBackgroundDepositRate: 12.2,
      agentSensorDegrees: 66,
      agentRotationRate: 7.2,
      agentSensorOffset: 1.17,
      agentSensorWidth: 0.53,
      agentStepSize: 1.78,
      agentCrowdAvoidance: 0.46,
      agentWanderStrength: 1.4,
      trailClockDecayRate: 0.47,
      trailClockDiffuseRate: 3,
      trailBackgroundDecayRate: 0.19,
      trailBackgroundDiffuseRate: 6.4,
    },
  },
  {
    name: "Unnamed Sim. 08 (Possibly 'Spectral')",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.17,
      agentClockDepositRate: 16.6,
      agentBackgroundDepositRate: 6.9,
      agentSensorDegrees: 41,
      agentRotationRate: 5.1,
      agentSensorOffset: 0.25,
      agentSensorWidth: 0.44,
      agentStepSize: 1.76,
      agentCrowdAvoidance: 0.26,
      agentWanderStrength: 6.6,
      trailClockDecayRate: 0.28,
      trailClockDiffuseRate: 14.3,
      trailBackgroundDecayRate: 0.72,
      trailBackgroundDiffuseRate: 5.1,
    },
  },
  {
    name: "Unnamed Sim. 09 (Possibly 'Spiderwebby')",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.65,
      agentClockDepositRate: 18.9,
      agentBackgroundDepositRate: 11.5,
      agentSensorDegrees: 15,
      agentRotationRate: 5,
      agentSensorOffset: 1.14,
      agentSensorWidth: 0.22,
      agentStepSize: 1,
      agentCrowdAvoidance: 0.33,
      agentWanderStrength: 4.4,
      trailClockDecayRate: 0.29,
      trailClockDiffuseRate: 9.9,
      trailBackgroundDecayRate: 0.69,
      trailBackgroundDiffuseRate: 2.1,
    },
  },
  {
    name: "Unnamed Sim. 10 (Possibly 'Slimy 07')",
    presetType: "Simulation Only",
    isBasePreset: true,
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 1,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.04,
      agentClockDepositRate: 8.3,
      agentBackgroundDepositRate: 7.3,
      agentSensorDegrees: 21,
      agentRotationRate: 3,
      agentSensorOffset: 1.06,
      agentSensorWidth: 0.16,
      agentStepSize: 1.29,
      agentCrowdAvoidance: 0.2,
      agentWanderStrength: 6.5,
      trailClockDecayRate: 0.05,
      trailClockDiffuseRate: 7.8,
      trailBackgroundDecayRate: 0.48,
      trailBackgroundDiffuseRate: 10.6,
    },
  },
  {
    name: "Unnamed Color 01",
    presetType: "Color Only",
    isBasePreset: true,
    colorSettings: {
      backgroundColor: "#e9f8be",
      slimeColorMode: "Procedural",
      proceduralColorPalette: {
        r: {
          yOffset: 0.52,
          amplitude: 0.66,
          frequency: 1.33,
          phase: 1.84,
        },
        g: {
          yOffset: 0.21,
          amplitude: 0.4,
          frequency: 0.99,
          phase: 0.93,
        },
        b: {
          yOffset: 0.32,
          amplitude: 0.75,
          frequency: 1.22,
          phase: 0.9,
        },
      },
      intensitySmoothing: 0.59,
      agentDirectionSmoothing: 0.68,
      agentDirectionColorOffset: 0.42,
      clockColorOffset: 0.64,
      xColorOffset: 0.65,
      yColorOffset: 0.8,
      paletteCycleSpeed: 0.54,
      paletteCycleScale: 0.1,
      paletteCycleType: 1,
    },
  },
  {
    name: "Unnamed Color 02",
    presetType: "Color Only",
    isBasePreset: true,
    colorSettings: {
      backgroundColor: "#1b7d34",
      slimeColorMode: "Procedural",
      proceduralColorPalette: {
        r: {
          yOffset: 0.49,
          amplitude: 0.66,
          frequency: 1.18,
          phase: 2.41,
        },
        g: {
          yOffset: 0.67,
          amplitude: 0.71,
          frequency: 0.7,
          phase: 1.17,
        },
        b: {
          yOffset: 0.4,
          amplitude: 0.61,
          frequency: 1.33,
          phase: 0.81,
        },
      },
      intensitySmoothing: 0.59,
      agentDirectionSmoothing: 0.68,
      agentDirectionColorOffset: 0.42,
      clockColorOffset: 0.64,
      xColorOffset: 0.65,
      yColorOffset: 0.8,
      paletteCycleSpeed: 0.54,
      paletteCycleScale: 0.1,
      paletteCycleType: 1,
    },
  },
  {
    name: "Unnamed Color 03",
    presetType: "Color Only",
    isBasePreset: true,
    colorSettings: {
      backgroundColor: "#000000",
      slimeColorMode: "Procedural",
      proceduralColorPalette: {
        r: {
          yOffset: 0.5,
          amplitude: 0.45,
          frequency: 1.12,
          phase: 1.14,
        },
        g: {
          yOffset: 0.88,
          amplitude: 0.49,
          frequency: 0.42,
          phase: 2.13,
        },
        b: {
          yOffset: 0.8,
          amplitude: 0.46,
          frequency: 1.39,
          phase: 1.55,
        },
      },
      intensitySmoothing: 0.94,
      agentDirectionSmoothing: 0.93,
      agentDirectionColorOffset: 0.12,
      clockColorOffset: 0.07,
      xColorOffset: -0.35,
      yColorOffset: 0.8,
      paletteCycleSpeed: 0.54,
      paletteCycleScale: 0.06,
      paletteCycleType: 0,
    },
  },
];
export const SINGLE_PRESET_TYPES: SingleSimulationPresetType[] = [
  "Clock Only",
  "Simulation Only",
  "Color Only",
];
export const MULTIPLE_PRESET_TYPES: MultipleSimulationPresetType[] = [
  "Combination",
];

// {
//   "clockSettings": {
//     "show": true,
//     "size": 20,
//     "digitLayout": "vertical",
//     "hourFormat": "24h",
//     "digitStyle": "14segment",
//     "padHours": true,
//     "showClockShadow": true,
//     "clockShadowOpacity": 0.25,
//     "clockShadowColor": "#6f6f6f"
//   },
//   "simulationSettings": {
//     "speed": 3.3,
//     "boundaryBehavior": 0,
//     "agentDensity": 0.25,
//     "agentStartType": -1,
//     "agentClockAttraction": 0.13,
//     "agentClockDepositRate": 7.9,
//     "agentBackgroundDepositRate": 5.6,
//     "agentSensorDegrees": 59,
//     "agentRotationRate": 3,
//     "agentSensorOffset": 1.02,
//     "agentSensorWidth": 0.14,
//     "agentStepSize": 1.05,
//     "agentCrowdAvoidance": 0.33,
//     "agentWanderStrength": 6.4,
//     "displayTextureAspectRatio": "Window",
//     "displayTextureTargetQuality": 2.1,
//     "trailClockDecayRate": 0.12,
//     "trailClockDiffuseRate": 5.1,
//     "trailBackgroundDecayRate": 0.39,
//     "trailBackgroundDiffuseRate": 11.2
//   },
//   "colorSettings": {
//     "backgroundColor": "#93e0d3",
//     "slimeColorMode": "Procedural",
//     "proceduralColorPalette": {
//       "r": {
//         "yOffset": 1,
//         "amplitude": 0.02,
//         "frequency": 0.09,
//         "phase": 1.07
//       },
//       "g": {
//         "yOffset": 0.08,
//         "amplitude": 0.71,
//         "frequency": 0.11,
//         "phase": 0.8
//       },
//       "b": {
//         "yOffset": 0.16,
//         "amplitude": 0.25,
//         "frequency": 2.1,
//         "phase": 1.43
//       }
//     },
//     "intensitySmoothing": 0.59,
//     "agentDirectionSmoothing": 0.68,
//     "agentDirectionColorOffset": 0.42,
//     "clockColorOffset": 0.64,
//     "xColorOffset": 0.65,
//     "yColorOffset": 0.8,
//     "paletteCycleSpeed": 0.54,
//     "paletteCycleScale": 0.1,
//     "paletteCycleType": 1
//   }
// }

// {
//   "clockSettings": {
//     "show": true,
//     "size": 20,
//     "digitLayout": "vertical",
//     "hourFormat": "24h",
//     "digitStyle": "14segment",
//     "padHours": true,
//     "showClockShadow": true,
//     "clockShadowOpacity": 0.25,
//     "clockShadowColor": "#6f6f6f"
//   },
//   "simulationSettings": {
//     "speed": 3.3,
//     "boundaryBehavior": 0,
//     "agentDensity": 0.25,
//     "agentStartType": -1,
//     "agentClockAttraction": 0.12,
//     "agentClockDepositRate": 8.2,
//     "agentBackgroundDepositRate": 5.7,
//     "agentSensorDegrees": 37,
//     "agentRotationRate": 2.3,
//     "agentSensorOffset": 0.51,
//     "agentSensorWidth": 0.26,
//     "agentStepSize": 2.04,
//     "agentCrowdAvoidance": 0.52,
//     "agentWanderStrength": 3,
//     "displayTextureAspectRatio": "Window",
//     "displayTextureTargetQuality": 2.1,
//     "trailClockDecayRate": 0.24,
//     "trailClockDiffuseRate": 3.4,
//     "trailBackgroundDecayRate": 0.21,
//     "trailBackgroundDiffuseRate": 9
//   },
//   "colorSettings": {
//     "backgroundColor": "#e45526",
//     "slimeColorMode": "Procedural",
//     "proceduralColorPalette": {
//       "r": {
//         "yOffset": 0.46,
//         "amplitude": 0.84,
//         "frequency": 1.2,
//         "phase": 0.89
//       },
//       "g": {
//         "yOffset": 0.39,
//         "amplitude": 0.25,
//         "frequency": 1.42,
//         "phase": 1.04
//       },
//       "b": {
//         "yOffset": 0.41,
//         "amplitude": 1.34,
//         "frequency": 1.22,
//         "phase": 1.55
//       }
//     },
//     "intensitySmoothing": 0.59,
//     "agentDirectionSmoothing": 0.68,
//     "agentDirectionColorOffset": 0.42,
//     "clockColorOffset": 0.64,
//     "xColorOffset": 0.65,
//     "yColorOffset": 0.8,
//     "paletteCycleSpeed": 0.54,
//     "paletteCycleScale": 0.1,
//     "paletteCycleType": 1
//   }
// }

// {
//   "clockSettings": {
//     "show": true,
//     "size": 22,
//     "digitLayout": "vertical",
//     "hourFormat": "24h",
//     "digitStyle": "roboto",
//     "padHours": true,
//     "showClockShadow": true,
//     "clockShadowOpacity": 0.09,
//     "clockShadowColor": "#6f6f6f"
//   },
//   "simulationSettings": {
//     "speed": 2.7,
//     "boundaryBehavior": 0,
//     "agentDensity": 0.25,
//     "agentStartType": -1,
//     "agentClockAttraction": 0.68,
//     "agentClockDepositRate": 12.3,
//     "agentBackgroundDepositRate": 5.1,
//     "agentSensorDegrees": 22,
//     "agentRotationRate": 2.3,
//     "agentSensorOffset": 0.51,
//     "agentSensorWidth": 0.15,
//     "agentStepSize": 0.53,
//     "agentCrowdAvoidance": 0.46,
//     "agentWanderStrength": 5.3,
//     "trailClockDecayRate": 0.48,
//     "trailClockDiffuseRate": 7.8,
//     "trailBackgroundDecayRate": 0.44,
//     "trailBackgroundDiffuseRate": 7.5
//   },
//   "colorSettings": {
//     "backgroundColor": "#000000",
//     "slimeColorMode": "Procedural",
//     "proceduralColorPalette": {
//       "r": {
//         "yOffset": 0.57,
//         "amplitude": 0.59,
//         "frequency": 1.28,
//         "phase": 1.72
//       },
//       "g": {
//         "yOffset": 0.82,
//         "amplitude": 0.57,
//         "frequency": 0.9,
//         "phase": 2.96
//       },
//       "b": {
//         "yOffset": 0.62,
//         "amplitude": 0.71,
//         "frequency": 0.99,
//         "phase": 2
//       }
//     },
//     "intensitySmoothing": 0.94,
//     "agentDirectionSmoothing": 0.93,
//     "agentDirectionColorOffset": 0.12,
//     "clockColorOffset": 0.07,
//     "xColorOffset": -0.35,
//     "yColorOffset": 0.8,
//     "paletteCycleSpeed": 0.54,
//     "paletteCycleScale": 0.06,
//     "paletteCycleType": 0
//   }
// }
