const toImplement: Array<unknown> = [
  {
    clockSettings: {
      show: true,
      size: 30,
      digitLayout: "vertical",
      hourFormat: "24h",
      digitStyle: "roboto",
      padHours: true,
      showClockShadow: true,
      clockShadowOpacity: 0.25,
      clockShadowColor: "#6f6f6f",
    },
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.08,
      agentClockDepositRate: 8.4,
      agentBackgroundDepositRate: 8,
      agentSensorDegrees: 26,
      agentRotationRate: 3.9,
      agentSensorOffset: 1.5,
      agentSensorWidth: 0.31,
      agentStepSize: 1.37,
      agentCrowdAvoidance: 0.17,
      agentWanderStrength: 5.8,
      trailClockDecayRate: 0.12,
      trailClockDiffuseRate: 8.4,
      trailBackgroundDecayRate: 0.49,
      trailBackgroundDiffuseRate: 9.6,
    },
    colorSettings: {
      backgroundColor: "#e9f8be",
      slimeColorMode: "Procedural",
      proceduralColorPalette: {
        r: {
          yOffset: 0.52,
          amplitude: 0.66,
          frequency: 1.33,
          phase: 1.84,
        },
        g: {
          yOffset: 0.21,
          amplitude: 0.4,
          frequency: 0.99,
          phase: 0.93,
        },
        b: {
          yOffset: 0.32,
          amplitude: 0.75,
          frequency: 1.22,
          phase: 0.9,
        },
      },
      intensitySmoothing: 0.59,
      agentDirectionSmoothing: 0.68,
      agentDirectionColorOffset: 0.42,
      clockColorOffset: 0.64,
      xColorOffset: 0.65,
      yColorOffset: 0.8,
      paletteCycleSpeed: 0.54,
      paletteCycleScale: 0.1,
      paletteCycleType: 1,
    },
  },
  {
    clockSettings: {
      show: true,
      size: 30,
      digitLayout: "vertical",
      hourFormat: "24h",
      digitStyle: "roboto",
      padHours: true,
      showClockShadow: true,
      clockShadowOpacity: 0.25,
      clockShadowColor: "#6f6f6f",
    },
    simulationSettings: {
      speed: 3.3,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.07,
      agentClockDepositRate: 6.4,
      agentBackgroundDepositRate: 8.3,
      agentSensorDegrees: 24,
      agentRotationRate: 4,
      agentSensorOffset: 1.21,
      agentSensorWidth: 0.25,
      agentStepSize: 1.24,
      agentCrowdAvoidance: 0.17,
      agentWanderStrength: 4.1,
      trailClockDecayRate: 0.04,
      trailClockDiffuseRate: 9.9,
      trailBackgroundDecayRate: 0.39,
      trailBackgroundDiffuseRate: 11.2,
    },
    colorSettings: {
      backgroundColor: "#1b7d34",
      slimeColorMode: "Procedural",
      proceduralColorPalette: {
        r: {
          yOffset: 0.49,
          amplitude: 0.66,
          frequency: 1.18,
          phase: 2.41,
        },
        g: {
          yOffset: 0.67,
          amplitude: 0.71,
          frequency: 0.7,
          phase: 1.17,
        },
        b: {
          yOffset: 0.4,
          amplitude: 0.61,
          frequency: 1.33,
          phase: 0.81,
        },
      },
      intensitySmoothing: 0.59,
      agentDirectionSmoothing: 0.68,
      agentDirectionColorOffset: 0.42,
      clockColorOffset: 0.64,
      xColorOffset: 0.65,
      yColorOffset: 0.8,
      paletteCycleSpeed: 0.54,
      paletteCycleScale: 0.1,
      paletteCycleType: 1,
    },
  },
  {
    clockSettings: {
      show: true,
      size: 22,
      digitLayout: "vertical",
      hourFormat: "24h",
      digitStyle: "roboto",
      padHours: true,
      showClockShadow: true,
      clockShadowOpacity: 0.09,
      clockShadowColor: "#6f6f6f",
    },
    simulationSettings: {
      speed: 2.7,
      boundaryBehavior: 0,
      agentDensity: 0.25,
      agentStartType: -1,
      agentClockAttraction: 0.72,
      agentClockDepositRate: 14.8,
      agentBackgroundDepositRate: 5,
      agentSensorDegrees: 31,
      agentRotationRate: 3.1,
      agentSensorOffset: 0.5,
      agentSensorWidth: 0.14,
      agentStepSize: 0.62,
      agentCrowdAvoidance: 0.5,
      agentWanderStrength: 3.8,
      trailClockDecayRate: 0.49,
      trailClockDiffuseRate: 8.6,
      trailBackgroundDecayRate: 0.56,
      trailBackgroundDiffuseRate: 7.8,
    },
    colorSettings: {
      backgroundColor: "#000000",
      slimeColorMode: "Procedural",
      proceduralColorPalette: {
        r: {
          yOffset: 0.5,
          amplitude: 0.45,
          frequency: 1.12,
          phase: 1.14,
        },
        g: {
          yOffset: 0.88,
          amplitude: 0.49,
          frequency: 0.42,
          phase: 2.13,
        },
        b: {
          yOffset: 0.8,
          amplitude: 0.46,
          frequency: 1.39,
          phase: 1.55,
        },
      },
      intensitySmoothing: 0.94,
      agentDirectionSmoothing: 0.93,
      agentDirectionColorOffset: 0.12,
      clockColorOffset: 0.07,
      xColorOffset: -0.35,
      yColorOffset: 0.8,
      paletteCycleSpeed: 0.54,
      paletteCycleScale: 0.06,
      paletteCycleType: 0,
    },
  },
];

console.log(toImplement);
